/* soapServer.c
   Generated by gSOAP 2.8.44 for SOF_interface.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.44 2017-06-07 10:36:53 GMT")
SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	soap->keep_alive = soap->max_keep_alive + 1;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->keep_alive > 0 && soap->max_keep_alive > 0)
			soap->keep_alive--;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if ((soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap))) && soap->error && soap->error < SOAP_STOP)
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}
#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_VerifySignedData"))
		return soap_serve___ns1__SOF_USCOREVerifySignedData(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_QueryCertTrustList"))
		return soap_serve___ns1__SOF_USCOREQueryCertTrustList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GetP7SignDataInfo"))
		return soap_serve___ns1__SOF_USCOREGetP7SignDataInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_SetCertTrustList"))
		return soap_serve___ns1__SOF_USCORESetCertTrustList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_VerifySignedDataByP7"))
		return soap_serve___ns1__SOF_USCOREVerifySignedDataByP7(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_PubKeyEncrypt"))
		return soap_serve___ns1__SOF_USCOREPubKeyEncrypt(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_VerifyTimeStamp"))
		return soap_serve___ns1__SOF_USCOREVerifyTimeStamp(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_VerifySignedFile"))
		return soap_serve___ns1__SOF_USCOREVerifySignedFile(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GetCertInfoByOid"))
		return soap_serve___ns1__SOF_USCOREGetCertInfoByOid(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GetServerCertificate"))
		return soap_serve___ns1__SOF_USCOREGetServerCertificate(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_DelCertTrustList"))
		return soap_serve___ns1__SOF_USCOREDelCertTrustList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GetXMLSignatureInfo"))
		return soap_serve___ns1__SOF_USCOREGetXMLSignatureInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_SignData"))
		return soap_serve___ns1__SOF_USCORESignData(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_VerifySignedDataXML"))
		return soap_serve___ns1__SOF_USCOREVerifySignedDataXML(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_SignFile"))
		return soap_serve___ns1__SOF_USCORESignFile(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GetInstance"))
		return soap_serve___ns1__SOF_USCOREGetInstance(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_PriKeyDecrypt"))
		return soap_serve___ns1__SOF_USCOREPriKeyDecrypt(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GenRandom"))
		return soap_serve___ns1__SOF_USCOREGenRandom(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GetSignMethod"))
		return soap_serve___ns1__SOF_USCOREGetSignMethod(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_SetWebAppName"))
		return soap_serve___ns1__SOF_USCORESetWebAppName(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_SetEncryptMethod"))
		return soap_serve___ns1__SOF_USCORESetEncryptMethod(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_CreateTimeStampRequest"))
		return soap_serve___ns1__SOF_USCORECreateTimeStampRequest(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GetEncryptMethod"))
		return soap_serve___ns1__SOF_USCOREGetEncryptMethod(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_CreateTimeStampResponse"))
		return soap_serve___ns1__SOF_USCORECreateTimeStampResponse(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_ValidateCert"))
		return soap_serve___ns1__SOF_USCOREValidateCert(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:DeleteFile"))
		return soap_serve___ns1__DeleteFile(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetFile"))
		return soap_serve___ns1__GetFile(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_DecryptFile"))
		return soap_serve___ns1__SOF_USCOREDecryptFile(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_SetSignMethod"))
		return soap_serve___ns1__SOF_USCORESetSignMethod(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GetTimeStampInfo"))
		return soap_serve___ns1__SOF_USCOREGetTimeStampInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_EncryptFile"))
		return soap_serve___ns1__SOF_USCOREEncryptFile(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_SignDataByP7"))
		return soap_serve___ns1__SOF_USCORESignDataByP7(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_DecryptData"))
		return soap_serve___ns1__SOF_USCOREDecryptData(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_SignDataXML"))
		return soap_serve___ns1__SOF_USCORESignDataXML(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GetCertInfo"))
		return soap_serve___ns1__SOF_USCOREGetCertInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_QueryCertTrustListAltNames"))
		return soap_serve___ns1__SOF_USCOREQueryCertTrustListAltNames(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_EncryptData"))
		return soap_serve___ns1__SOF_USCOREEncryptData(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREVerifySignedData(struct soap *soap)
{	struct __ns1__SOF_USCOREVerifySignedData soap_tmp___ns1__SOF_USCOREVerifySignedData;
	struct ns1__SOF_USCOREVerifySignedDataResponse ns1__SOF_USCOREVerifySignedDataResponse;
	soap_default_ns1__SOF_USCOREVerifySignedDataResponse(soap, &ns1__SOF_USCOREVerifySignedDataResponse);
	soap_default___ns1__SOF_USCOREVerifySignedData(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedData);
	if (!soap_get___ns1__SOF_USCOREVerifySignedData(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedData, "-ns1:SOF_VerifySignedData", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREVerifySignedData(soap, soap_tmp___ns1__SOF_USCOREVerifySignedData.ns1__SOF_USCOREVerifySignedData, &ns1__SOF_USCOREVerifySignedDataResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREVerifySignedDataResponse(soap, &ns1__SOF_USCOREVerifySignedDataResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREVerifySignedDataResponse(soap, &ns1__SOF_USCOREVerifySignedDataResponse, "ns1:SOF_VerifySignedDataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREVerifySignedDataResponse(soap, &ns1__SOF_USCOREVerifySignedDataResponse, "ns1:SOF_VerifySignedDataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREQueryCertTrustList(struct soap *soap)
{	struct __ns1__SOF_USCOREQueryCertTrustList soap_tmp___ns1__SOF_USCOREQueryCertTrustList;
	struct ns1__SOF_USCOREQueryCertTrustListResponse ns1__SOF_USCOREQueryCertTrustListResponse;
	soap_default_ns1__SOF_USCOREQueryCertTrustListResponse(soap, &ns1__SOF_USCOREQueryCertTrustListResponse);
	soap_default___ns1__SOF_USCOREQueryCertTrustList(soap, &soap_tmp___ns1__SOF_USCOREQueryCertTrustList);
	if (!soap_get___ns1__SOF_USCOREQueryCertTrustList(soap, &soap_tmp___ns1__SOF_USCOREQueryCertTrustList, "-ns1:SOF_QueryCertTrustList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREQueryCertTrustList(soap, soap_tmp___ns1__SOF_USCOREQueryCertTrustList.ns1__SOF_USCOREQueryCertTrustList, &ns1__SOF_USCOREQueryCertTrustListResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREQueryCertTrustListResponse(soap, &ns1__SOF_USCOREQueryCertTrustListResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREQueryCertTrustListResponse(soap, &ns1__SOF_USCOREQueryCertTrustListResponse, "ns1:SOF_QueryCertTrustListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREQueryCertTrustListResponse(soap, &ns1__SOF_USCOREQueryCertTrustListResponse, "ns1:SOF_QueryCertTrustListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGetP7SignDataInfo(struct soap *soap)
{	struct __ns1__SOF_USCOREGetP7SignDataInfo soap_tmp___ns1__SOF_USCOREGetP7SignDataInfo;
	struct ns1__SOF_USCOREGetP7SignDataInfoResponse ns1__SOF_USCOREGetP7SignDataInfoResponse;
	soap_default_ns1__SOF_USCOREGetP7SignDataInfoResponse(soap, &ns1__SOF_USCOREGetP7SignDataInfoResponse);
	soap_default___ns1__SOF_USCOREGetP7SignDataInfo(soap, &soap_tmp___ns1__SOF_USCOREGetP7SignDataInfo);
	if (!soap_get___ns1__SOF_USCOREGetP7SignDataInfo(soap, &soap_tmp___ns1__SOF_USCOREGetP7SignDataInfo, "-ns1:SOF_GetP7SignDataInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGetP7SignDataInfo(soap, soap_tmp___ns1__SOF_USCOREGetP7SignDataInfo.ns1__SOF_USCOREGetP7SignDataInfo, &ns1__SOF_USCOREGetP7SignDataInfoResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREGetP7SignDataInfoResponse(soap, &ns1__SOF_USCOREGetP7SignDataInfoResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREGetP7SignDataInfoResponse(soap, &ns1__SOF_USCOREGetP7SignDataInfoResponse, "ns1:SOF_GetP7SignDataInfoResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREGetP7SignDataInfoResponse(soap, &ns1__SOF_USCOREGetP7SignDataInfoResponse, "ns1:SOF_GetP7SignDataInfoResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORESetCertTrustList(struct soap *soap)
{	struct __ns1__SOF_USCORESetCertTrustList soap_tmp___ns1__SOF_USCORESetCertTrustList;
	struct ns1__SOF_USCORESetCertTrustListResponse ns1__SOF_USCORESetCertTrustListResponse;
	soap_default_ns1__SOF_USCORESetCertTrustListResponse(soap, &ns1__SOF_USCORESetCertTrustListResponse);
	soap_default___ns1__SOF_USCORESetCertTrustList(soap, &soap_tmp___ns1__SOF_USCORESetCertTrustList);
	if (!soap_get___ns1__SOF_USCORESetCertTrustList(soap, &soap_tmp___ns1__SOF_USCORESetCertTrustList, "-ns1:SOF_SetCertTrustList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORESetCertTrustList(soap, soap_tmp___ns1__SOF_USCORESetCertTrustList.ns1__SOF_USCORESetCertTrustList, &ns1__SOF_USCORESetCertTrustListResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCORESetCertTrustListResponse(soap, &ns1__SOF_USCORESetCertTrustListResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCORESetCertTrustListResponse(soap, &ns1__SOF_USCORESetCertTrustListResponse, "ns1:SOF_SetCertTrustListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCORESetCertTrustListResponse(soap, &ns1__SOF_USCORESetCertTrustListResponse, "ns1:SOF_SetCertTrustListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREVerifySignedDataByP7(struct soap *soap)
{	struct __ns1__SOF_USCOREVerifySignedDataByP7 soap_tmp___ns1__SOF_USCOREVerifySignedDataByP7;
	struct ns1__SOF_USCOREVerifySignedDataByP7Response ns1__SOF_USCOREVerifySignedDataByP7Response;
	soap_default_ns1__SOF_USCOREVerifySignedDataByP7Response(soap, &ns1__SOF_USCOREVerifySignedDataByP7Response);
	soap_default___ns1__SOF_USCOREVerifySignedDataByP7(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedDataByP7);
	if (!soap_get___ns1__SOF_USCOREVerifySignedDataByP7(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedDataByP7, "-ns1:SOF_VerifySignedDataByP7", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREVerifySignedDataByP7(soap, soap_tmp___ns1__SOF_USCOREVerifySignedDataByP7.ns1__SOF_USCOREVerifySignedDataByP7, &ns1__SOF_USCOREVerifySignedDataByP7Response);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREVerifySignedDataByP7Response(soap, &ns1__SOF_USCOREVerifySignedDataByP7Response);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREVerifySignedDataByP7Response(soap, &ns1__SOF_USCOREVerifySignedDataByP7Response, "ns1:SOF_VerifySignedDataByP7Response", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREVerifySignedDataByP7Response(soap, &ns1__SOF_USCOREVerifySignedDataByP7Response, "ns1:SOF_VerifySignedDataByP7Response", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREPubKeyEncrypt(struct soap *soap)
{	struct __ns1__SOF_USCOREPubKeyEncrypt soap_tmp___ns1__SOF_USCOREPubKeyEncrypt;
	struct ns1__SOF_USCOREPubKeyEncryptResponse ns1__SOF_USCOREPubKeyEncryptResponse;
	soap_default_ns1__SOF_USCOREPubKeyEncryptResponse(soap, &ns1__SOF_USCOREPubKeyEncryptResponse);
	soap_default___ns1__SOF_USCOREPubKeyEncrypt(soap, &soap_tmp___ns1__SOF_USCOREPubKeyEncrypt);
	if (!soap_get___ns1__SOF_USCOREPubKeyEncrypt(soap, &soap_tmp___ns1__SOF_USCOREPubKeyEncrypt, "-ns1:SOF_PubKeyEncrypt", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREPubKeyEncrypt(soap, soap_tmp___ns1__SOF_USCOREPubKeyEncrypt.ns1__SOF_USCOREPubKeyEncrypt, &ns1__SOF_USCOREPubKeyEncryptResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREPubKeyEncryptResponse(soap, &ns1__SOF_USCOREPubKeyEncryptResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREPubKeyEncryptResponse(soap, &ns1__SOF_USCOREPubKeyEncryptResponse, "ns1:SOF_PubKeyEncryptResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREPubKeyEncryptResponse(soap, &ns1__SOF_USCOREPubKeyEncryptResponse, "ns1:SOF_PubKeyEncryptResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREVerifyTimeStamp(struct soap *soap)
{	struct __ns1__SOF_USCOREVerifyTimeStamp soap_tmp___ns1__SOF_USCOREVerifyTimeStamp;
	struct ns1__SOF_USCOREVerifyTimeStampResponse ns1__SOF_USCOREVerifyTimeStampResponse;
	soap_default_ns1__SOF_USCOREVerifyTimeStampResponse(soap, &ns1__SOF_USCOREVerifyTimeStampResponse);
	soap_default___ns1__SOF_USCOREVerifyTimeStamp(soap, &soap_tmp___ns1__SOF_USCOREVerifyTimeStamp);
	if (!soap_get___ns1__SOF_USCOREVerifyTimeStamp(soap, &soap_tmp___ns1__SOF_USCOREVerifyTimeStamp, "-ns1:SOF_VerifyTimeStamp", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREVerifyTimeStamp(soap, soap_tmp___ns1__SOF_USCOREVerifyTimeStamp.ns1__SOF_USCOREVerifyTimeStamp, &ns1__SOF_USCOREVerifyTimeStampResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREVerifyTimeStampResponse(soap, &ns1__SOF_USCOREVerifyTimeStampResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREVerifyTimeStampResponse(soap, &ns1__SOF_USCOREVerifyTimeStampResponse, "ns1:SOF_VerifyTimeStampResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREVerifyTimeStampResponse(soap, &ns1__SOF_USCOREVerifyTimeStampResponse, "ns1:SOF_VerifyTimeStampResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREVerifySignedFile(struct soap *soap)
{	struct __ns1__SOF_USCOREVerifySignedFile soap_tmp___ns1__SOF_USCOREVerifySignedFile;
	struct ns1__SOF_USCOREVerifySignedFileResponse ns1__SOF_USCOREVerifySignedFileResponse;
	soap_default_ns1__SOF_USCOREVerifySignedFileResponse(soap, &ns1__SOF_USCOREVerifySignedFileResponse);
	soap_default___ns1__SOF_USCOREVerifySignedFile(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedFile);
	if (!soap_get___ns1__SOF_USCOREVerifySignedFile(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedFile, "-ns1:SOF_VerifySignedFile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREVerifySignedFile(soap, soap_tmp___ns1__SOF_USCOREVerifySignedFile.ns1__SOF_USCOREVerifySignedFile, &ns1__SOF_USCOREVerifySignedFileResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREVerifySignedFileResponse(soap, &ns1__SOF_USCOREVerifySignedFileResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREVerifySignedFileResponse(soap, &ns1__SOF_USCOREVerifySignedFileResponse, "ns1:SOF_VerifySignedFileResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREVerifySignedFileResponse(soap, &ns1__SOF_USCOREVerifySignedFileResponse, "ns1:SOF_VerifySignedFileResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGetCertInfoByOid(struct soap *soap)
{	struct __ns1__SOF_USCOREGetCertInfoByOid soap_tmp___ns1__SOF_USCOREGetCertInfoByOid;
	struct ns1__SOF_USCOREGetCertInfoByOidResponse ns1__SOF_USCOREGetCertInfoByOidResponse;
	soap_default_ns1__SOF_USCOREGetCertInfoByOidResponse(soap, &ns1__SOF_USCOREGetCertInfoByOidResponse);
	soap_default___ns1__SOF_USCOREGetCertInfoByOid(soap, &soap_tmp___ns1__SOF_USCOREGetCertInfoByOid);
	if (!soap_get___ns1__SOF_USCOREGetCertInfoByOid(soap, &soap_tmp___ns1__SOF_USCOREGetCertInfoByOid, "-ns1:SOF_GetCertInfoByOid", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGetCertInfoByOid(soap, soap_tmp___ns1__SOF_USCOREGetCertInfoByOid.ns1__SOF_USCOREGetCertInfoByOid, &ns1__SOF_USCOREGetCertInfoByOidResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREGetCertInfoByOidResponse(soap, &ns1__SOF_USCOREGetCertInfoByOidResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREGetCertInfoByOidResponse(soap, &ns1__SOF_USCOREGetCertInfoByOidResponse, "ns1:SOF_GetCertInfoByOidResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREGetCertInfoByOidResponse(soap, &ns1__SOF_USCOREGetCertInfoByOidResponse, "ns1:SOF_GetCertInfoByOidResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGetServerCertificate(struct soap *soap)
{	struct __ns1__SOF_USCOREGetServerCertificate soap_tmp___ns1__SOF_USCOREGetServerCertificate;
	struct ns1__SOF_USCOREGetServerCertificateResponse ns1__SOF_USCOREGetServerCertificateResponse;
	soap_default_ns1__SOF_USCOREGetServerCertificateResponse(soap, &ns1__SOF_USCOREGetServerCertificateResponse);
	soap_default___ns1__SOF_USCOREGetServerCertificate(soap, &soap_tmp___ns1__SOF_USCOREGetServerCertificate);
	if (!soap_get___ns1__SOF_USCOREGetServerCertificate(soap, &soap_tmp___ns1__SOF_USCOREGetServerCertificate, "-ns1:SOF_GetServerCertificate", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGetServerCertificate(soap, soap_tmp___ns1__SOF_USCOREGetServerCertificate.ns1__SOF_USCOREGetServerCertificate, &ns1__SOF_USCOREGetServerCertificateResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREGetServerCertificateResponse(soap, &ns1__SOF_USCOREGetServerCertificateResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREGetServerCertificateResponse(soap, &ns1__SOF_USCOREGetServerCertificateResponse, "ns1:SOF_GetServerCertificateResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREGetServerCertificateResponse(soap, &ns1__SOF_USCOREGetServerCertificateResponse, "ns1:SOF_GetServerCertificateResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREDelCertTrustList(struct soap *soap)
{	struct __ns1__SOF_USCOREDelCertTrustList soap_tmp___ns1__SOF_USCOREDelCertTrustList;
	struct ns1__SOF_USCOREDelCertTrustListResponse ns1__SOF_USCOREDelCertTrustListResponse;
	soap_default_ns1__SOF_USCOREDelCertTrustListResponse(soap, &ns1__SOF_USCOREDelCertTrustListResponse);
	soap_default___ns1__SOF_USCOREDelCertTrustList(soap, &soap_tmp___ns1__SOF_USCOREDelCertTrustList);
	if (!soap_get___ns1__SOF_USCOREDelCertTrustList(soap, &soap_tmp___ns1__SOF_USCOREDelCertTrustList, "-ns1:SOF_DelCertTrustList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREDelCertTrustList(soap, soap_tmp___ns1__SOF_USCOREDelCertTrustList.ns1__SOF_USCOREDelCertTrustList, &ns1__SOF_USCOREDelCertTrustListResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREDelCertTrustListResponse(soap, &ns1__SOF_USCOREDelCertTrustListResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREDelCertTrustListResponse(soap, &ns1__SOF_USCOREDelCertTrustListResponse, "ns1:SOF_DelCertTrustListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREDelCertTrustListResponse(soap, &ns1__SOF_USCOREDelCertTrustListResponse, "ns1:SOF_DelCertTrustListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGetXMLSignatureInfo(struct soap *soap)
{	struct __ns1__SOF_USCOREGetXMLSignatureInfo soap_tmp___ns1__SOF_USCOREGetXMLSignatureInfo;
	struct ns1__SOF_USCOREGetXMLSignatureInfoResponse ns1__SOF_USCOREGetXMLSignatureInfoResponse;
	soap_default_ns1__SOF_USCOREGetXMLSignatureInfoResponse(soap, &ns1__SOF_USCOREGetXMLSignatureInfoResponse);
	soap_default___ns1__SOF_USCOREGetXMLSignatureInfo(soap, &soap_tmp___ns1__SOF_USCOREGetXMLSignatureInfo);
	if (!soap_get___ns1__SOF_USCOREGetXMLSignatureInfo(soap, &soap_tmp___ns1__SOF_USCOREGetXMLSignatureInfo, "-ns1:SOF_GetXMLSignatureInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGetXMLSignatureInfo(soap, soap_tmp___ns1__SOF_USCOREGetXMLSignatureInfo.ns1__SOF_USCOREGetXMLSignatureInfo, &ns1__SOF_USCOREGetXMLSignatureInfoResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREGetXMLSignatureInfoResponse(soap, &ns1__SOF_USCOREGetXMLSignatureInfoResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREGetXMLSignatureInfoResponse(soap, &ns1__SOF_USCOREGetXMLSignatureInfoResponse, "ns1:SOF_GetXMLSignatureInfoResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREGetXMLSignatureInfoResponse(soap, &ns1__SOF_USCOREGetXMLSignatureInfoResponse, "ns1:SOF_GetXMLSignatureInfoResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORESignData(struct soap *soap)
{	struct __ns1__SOF_USCORESignData soap_tmp___ns1__SOF_USCORESignData;
	struct ns1__SOF_USCORESignDataResponse ns1__SOF_USCORESignDataResponse;
	soap_default_ns1__SOF_USCORESignDataResponse(soap, &ns1__SOF_USCORESignDataResponse);
	soap_default___ns1__SOF_USCORESignData(soap, &soap_tmp___ns1__SOF_USCORESignData);
	if (!soap_get___ns1__SOF_USCORESignData(soap, &soap_tmp___ns1__SOF_USCORESignData, "-ns1:SOF_SignData", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORESignData(soap, soap_tmp___ns1__SOF_USCORESignData.ns1__SOF_USCORESignData, &ns1__SOF_USCORESignDataResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCORESignDataResponse(soap, &ns1__SOF_USCORESignDataResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCORESignDataResponse(soap, &ns1__SOF_USCORESignDataResponse, "ns1:SOF_SignDataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCORESignDataResponse(soap, &ns1__SOF_USCORESignDataResponse, "ns1:SOF_SignDataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREVerifySignedDataXML(struct soap *soap)
{	struct __ns1__SOF_USCOREVerifySignedDataXML soap_tmp___ns1__SOF_USCOREVerifySignedDataXML;
	struct ns1__SOF_USCOREVerifySignedDataXMLResponse ns1__SOF_USCOREVerifySignedDataXMLResponse;
	soap_default_ns1__SOF_USCOREVerifySignedDataXMLResponse(soap, &ns1__SOF_USCOREVerifySignedDataXMLResponse);
	soap_default___ns1__SOF_USCOREVerifySignedDataXML(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedDataXML);
	if (!soap_get___ns1__SOF_USCOREVerifySignedDataXML(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedDataXML, "-ns1:SOF_VerifySignedDataXML", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREVerifySignedDataXML(soap, soap_tmp___ns1__SOF_USCOREVerifySignedDataXML.ns1__SOF_USCOREVerifySignedDataXML, &ns1__SOF_USCOREVerifySignedDataXMLResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREVerifySignedDataXMLResponse(soap, &ns1__SOF_USCOREVerifySignedDataXMLResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREVerifySignedDataXMLResponse(soap, &ns1__SOF_USCOREVerifySignedDataXMLResponse, "ns1:SOF_VerifySignedDataXMLResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREVerifySignedDataXMLResponse(soap, &ns1__SOF_USCOREVerifySignedDataXMLResponse, "ns1:SOF_VerifySignedDataXMLResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORESignFile(struct soap *soap)
{	struct __ns1__SOF_USCORESignFile soap_tmp___ns1__SOF_USCORESignFile;
	struct ns1__SOF_USCORESignFileResponse ns1__SOF_USCORESignFileResponse;
	soap_default_ns1__SOF_USCORESignFileResponse(soap, &ns1__SOF_USCORESignFileResponse);
	soap_default___ns1__SOF_USCORESignFile(soap, &soap_tmp___ns1__SOF_USCORESignFile);
	if (!soap_get___ns1__SOF_USCORESignFile(soap, &soap_tmp___ns1__SOF_USCORESignFile, "-ns1:SOF_SignFile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORESignFile(soap, soap_tmp___ns1__SOF_USCORESignFile.ns1__SOF_USCORESignFile, &ns1__SOF_USCORESignFileResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCORESignFileResponse(soap, &ns1__SOF_USCORESignFileResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCORESignFileResponse(soap, &ns1__SOF_USCORESignFileResponse, "ns1:SOF_SignFileResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCORESignFileResponse(soap, &ns1__SOF_USCORESignFileResponse, "ns1:SOF_SignFileResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGetInstance(struct soap *soap)
{	struct __ns1__SOF_USCOREGetInstance soap_tmp___ns1__SOF_USCOREGetInstance;
	struct ns1__SOF_USCOREGetInstanceResponse ns1__SOF_USCOREGetInstanceResponse;
	soap_default_ns1__SOF_USCOREGetInstanceResponse(soap, &ns1__SOF_USCOREGetInstanceResponse);
	soap_default___ns1__SOF_USCOREGetInstance(soap, &soap_tmp___ns1__SOF_USCOREGetInstance);
	if (!soap_get___ns1__SOF_USCOREGetInstance(soap, &soap_tmp___ns1__SOF_USCOREGetInstance, "-ns1:SOF_GetInstance", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGetInstance(soap, soap_tmp___ns1__SOF_USCOREGetInstance.ns1__SOF_USCOREGetInstance, &ns1__SOF_USCOREGetInstanceResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREGetInstanceResponse(soap, &ns1__SOF_USCOREGetInstanceResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREGetInstanceResponse(soap, &ns1__SOF_USCOREGetInstanceResponse, "ns1:SOF_GetInstanceResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREGetInstanceResponse(soap, &ns1__SOF_USCOREGetInstanceResponse, "ns1:SOF_GetInstanceResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREPriKeyDecrypt(struct soap *soap)
{	struct __ns1__SOF_USCOREPriKeyDecrypt soap_tmp___ns1__SOF_USCOREPriKeyDecrypt;
	struct ns1__SOF_USCOREPriKeyDecryptResponse ns1__SOF_USCOREPriKeyDecryptResponse;
	soap_default_ns1__SOF_USCOREPriKeyDecryptResponse(soap, &ns1__SOF_USCOREPriKeyDecryptResponse);
	soap_default___ns1__SOF_USCOREPriKeyDecrypt(soap, &soap_tmp___ns1__SOF_USCOREPriKeyDecrypt);
	if (!soap_get___ns1__SOF_USCOREPriKeyDecrypt(soap, &soap_tmp___ns1__SOF_USCOREPriKeyDecrypt, "-ns1:SOF_PriKeyDecrypt", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREPriKeyDecrypt(soap, soap_tmp___ns1__SOF_USCOREPriKeyDecrypt.ns1__SOF_USCOREPriKeyDecrypt, &ns1__SOF_USCOREPriKeyDecryptResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREPriKeyDecryptResponse(soap, &ns1__SOF_USCOREPriKeyDecryptResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREPriKeyDecryptResponse(soap, &ns1__SOF_USCOREPriKeyDecryptResponse, "ns1:SOF_PriKeyDecryptResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREPriKeyDecryptResponse(soap, &ns1__SOF_USCOREPriKeyDecryptResponse, "ns1:SOF_PriKeyDecryptResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGenRandom(struct soap *soap)
{	struct __ns1__SOF_USCOREGenRandom soap_tmp___ns1__SOF_USCOREGenRandom;
	struct ns1__SOF_USCOREGenRandomResponse ns1__SOF_USCOREGenRandomResponse;
	soap_default_ns1__SOF_USCOREGenRandomResponse(soap, &ns1__SOF_USCOREGenRandomResponse);
	soap_default___ns1__SOF_USCOREGenRandom(soap, &soap_tmp___ns1__SOF_USCOREGenRandom);
	if (!soap_get___ns1__SOF_USCOREGenRandom(soap, &soap_tmp___ns1__SOF_USCOREGenRandom, "-ns1:SOF_GenRandom", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGenRandom(soap, soap_tmp___ns1__SOF_USCOREGenRandom.ns1__SOF_USCOREGenRandom, &ns1__SOF_USCOREGenRandomResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREGenRandomResponse(soap, &ns1__SOF_USCOREGenRandomResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREGenRandomResponse(soap, &ns1__SOF_USCOREGenRandomResponse, "ns1:SOF_GenRandomResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREGenRandomResponse(soap, &ns1__SOF_USCOREGenRandomResponse, "ns1:SOF_GenRandomResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGetSignMethod(struct soap *soap)
{	struct __ns1__SOF_USCOREGetSignMethod soap_tmp___ns1__SOF_USCOREGetSignMethod;
	struct ns1__SOF_USCOREGetSignMethodResponse ns1__SOF_USCOREGetSignMethodResponse;
	soap_default_ns1__SOF_USCOREGetSignMethodResponse(soap, &ns1__SOF_USCOREGetSignMethodResponse);
	soap_default___ns1__SOF_USCOREGetSignMethod(soap, &soap_tmp___ns1__SOF_USCOREGetSignMethod);
	if (!soap_get___ns1__SOF_USCOREGetSignMethod(soap, &soap_tmp___ns1__SOF_USCOREGetSignMethod, "-ns1:SOF_GetSignMethod", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGetSignMethod(soap, soap_tmp___ns1__SOF_USCOREGetSignMethod.ns1__SOF_USCOREGetSignMethod, &ns1__SOF_USCOREGetSignMethodResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREGetSignMethodResponse(soap, &ns1__SOF_USCOREGetSignMethodResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREGetSignMethodResponse(soap, &ns1__SOF_USCOREGetSignMethodResponse, "ns1:SOF_GetSignMethodResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREGetSignMethodResponse(soap, &ns1__SOF_USCOREGetSignMethodResponse, "ns1:SOF_GetSignMethodResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORESetWebAppName(struct soap *soap)
{	struct __ns1__SOF_USCORESetWebAppName soap_tmp___ns1__SOF_USCORESetWebAppName;
	struct ns1__SOF_USCORESetWebAppNameResponse ns1__SOF_USCORESetWebAppNameResponse;
	soap_default_ns1__SOF_USCORESetWebAppNameResponse(soap, &ns1__SOF_USCORESetWebAppNameResponse);
	soap_default___ns1__SOF_USCORESetWebAppName(soap, &soap_tmp___ns1__SOF_USCORESetWebAppName);
	if (!soap_get___ns1__SOF_USCORESetWebAppName(soap, &soap_tmp___ns1__SOF_USCORESetWebAppName, "-ns1:SOF_SetWebAppName", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORESetWebAppName(soap, soap_tmp___ns1__SOF_USCORESetWebAppName.ns1__SOF_USCORESetWebAppName, &ns1__SOF_USCORESetWebAppNameResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCORESetWebAppNameResponse(soap, &ns1__SOF_USCORESetWebAppNameResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCORESetWebAppNameResponse(soap, &ns1__SOF_USCORESetWebAppNameResponse, "ns1:SOF_SetWebAppNameResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCORESetWebAppNameResponse(soap, &ns1__SOF_USCORESetWebAppNameResponse, "ns1:SOF_SetWebAppNameResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORESetEncryptMethod(struct soap *soap)
{	struct __ns1__SOF_USCORESetEncryptMethod soap_tmp___ns1__SOF_USCORESetEncryptMethod;
	struct ns1__SOF_USCORESetEncryptMethodResponse ns1__SOF_USCORESetEncryptMethodResponse;
	soap_default_ns1__SOF_USCORESetEncryptMethodResponse(soap, &ns1__SOF_USCORESetEncryptMethodResponse);
	soap_default___ns1__SOF_USCORESetEncryptMethod(soap, &soap_tmp___ns1__SOF_USCORESetEncryptMethod);
	if (!soap_get___ns1__SOF_USCORESetEncryptMethod(soap, &soap_tmp___ns1__SOF_USCORESetEncryptMethod, "-ns1:SOF_SetEncryptMethod", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORESetEncryptMethod(soap, soap_tmp___ns1__SOF_USCORESetEncryptMethod.ns1__SOF_USCORESetEncryptMethod, &ns1__SOF_USCORESetEncryptMethodResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCORESetEncryptMethodResponse(soap, &ns1__SOF_USCORESetEncryptMethodResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCORESetEncryptMethodResponse(soap, &ns1__SOF_USCORESetEncryptMethodResponse, "ns1:SOF_SetEncryptMethodResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCORESetEncryptMethodResponse(soap, &ns1__SOF_USCORESetEncryptMethodResponse, "ns1:SOF_SetEncryptMethodResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORECreateTimeStampRequest(struct soap *soap)
{	struct __ns1__SOF_USCORECreateTimeStampRequest soap_tmp___ns1__SOF_USCORECreateTimeStampRequest;
	struct ns1__SOF_USCORECreateTimeStampRequestResponse ns1__SOF_USCORECreateTimeStampRequestResponse;
	soap_default_ns1__SOF_USCORECreateTimeStampRequestResponse(soap, &ns1__SOF_USCORECreateTimeStampRequestResponse);
	soap_default___ns1__SOF_USCORECreateTimeStampRequest(soap, &soap_tmp___ns1__SOF_USCORECreateTimeStampRequest);
	if (!soap_get___ns1__SOF_USCORECreateTimeStampRequest(soap, &soap_tmp___ns1__SOF_USCORECreateTimeStampRequest, "-ns1:SOF_CreateTimeStampRequest", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORECreateTimeStampRequest(soap, soap_tmp___ns1__SOF_USCORECreateTimeStampRequest.ns1__SOF_USCORECreateTimeStampRequest, &ns1__SOF_USCORECreateTimeStampRequestResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCORECreateTimeStampRequestResponse(soap, &ns1__SOF_USCORECreateTimeStampRequestResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCORECreateTimeStampRequestResponse(soap, &ns1__SOF_USCORECreateTimeStampRequestResponse, "ns1:SOF_CreateTimeStampRequestResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCORECreateTimeStampRequestResponse(soap, &ns1__SOF_USCORECreateTimeStampRequestResponse, "ns1:SOF_CreateTimeStampRequestResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGetEncryptMethod(struct soap *soap)
{	struct __ns1__SOF_USCOREGetEncryptMethod soap_tmp___ns1__SOF_USCOREGetEncryptMethod;
	struct ns1__SOF_USCOREGetEncryptMethodResponse ns1__SOF_USCOREGetEncryptMethodResponse;
	soap_default_ns1__SOF_USCOREGetEncryptMethodResponse(soap, &ns1__SOF_USCOREGetEncryptMethodResponse);
	soap_default___ns1__SOF_USCOREGetEncryptMethod(soap, &soap_tmp___ns1__SOF_USCOREGetEncryptMethod);
	if (!soap_get___ns1__SOF_USCOREGetEncryptMethod(soap, &soap_tmp___ns1__SOF_USCOREGetEncryptMethod, "-ns1:SOF_GetEncryptMethod", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGetEncryptMethod(soap, soap_tmp___ns1__SOF_USCOREGetEncryptMethod.ns1__SOF_USCOREGetEncryptMethod, &ns1__SOF_USCOREGetEncryptMethodResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREGetEncryptMethodResponse(soap, &ns1__SOF_USCOREGetEncryptMethodResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREGetEncryptMethodResponse(soap, &ns1__SOF_USCOREGetEncryptMethodResponse, "ns1:SOF_GetEncryptMethodResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREGetEncryptMethodResponse(soap, &ns1__SOF_USCOREGetEncryptMethodResponse, "ns1:SOF_GetEncryptMethodResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORECreateTimeStampResponse(struct soap *soap)
{	struct __ns1__SOF_USCORECreateTimeStampResponse soap_tmp___ns1__SOF_USCORECreateTimeStampResponse;
	struct ns1__SOF_USCORECreateTimeStampResponseResponse ns1__SOF_USCORECreateTimeStampResponseResponse;
	soap_default_ns1__SOF_USCORECreateTimeStampResponseResponse(soap, &ns1__SOF_USCORECreateTimeStampResponseResponse);
	soap_default___ns1__SOF_USCORECreateTimeStampResponse(soap, &soap_tmp___ns1__SOF_USCORECreateTimeStampResponse);
	if (!soap_get___ns1__SOF_USCORECreateTimeStampResponse(soap, &soap_tmp___ns1__SOF_USCORECreateTimeStampResponse, "-ns1:SOF_CreateTimeStampResponse", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORECreateTimeStampResponse(soap, soap_tmp___ns1__SOF_USCORECreateTimeStampResponse.ns1__SOF_USCORECreateTimeStampResponse, &ns1__SOF_USCORECreateTimeStampResponseResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCORECreateTimeStampResponseResponse(soap, &ns1__SOF_USCORECreateTimeStampResponseResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCORECreateTimeStampResponseResponse(soap, &ns1__SOF_USCORECreateTimeStampResponseResponse, "ns1:SOF_CreateTimeStampResponseResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCORECreateTimeStampResponseResponse(soap, &ns1__SOF_USCORECreateTimeStampResponseResponse, "ns1:SOF_CreateTimeStampResponseResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREValidateCert(struct soap *soap)
{	struct __ns1__SOF_USCOREValidateCert soap_tmp___ns1__SOF_USCOREValidateCert;
	struct ns1__SOF_USCOREValidateCertResponse ns1__SOF_USCOREValidateCertResponse;
	soap_default_ns1__SOF_USCOREValidateCertResponse(soap, &ns1__SOF_USCOREValidateCertResponse);
	soap_default___ns1__SOF_USCOREValidateCert(soap, &soap_tmp___ns1__SOF_USCOREValidateCert);
	if (!soap_get___ns1__SOF_USCOREValidateCert(soap, &soap_tmp___ns1__SOF_USCOREValidateCert, "-ns1:SOF_ValidateCert", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREValidateCert(soap, soap_tmp___ns1__SOF_USCOREValidateCert.ns1__SOF_USCOREValidateCert, &ns1__SOF_USCOREValidateCertResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREValidateCertResponse(soap, &ns1__SOF_USCOREValidateCertResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREValidateCertResponse(soap, &ns1__SOF_USCOREValidateCertResponse, "ns1:SOF_ValidateCertResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREValidateCertResponse(soap, &ns1__SOF_USCOREValidateCertResponse, "ns1:SOF_ValidateCertResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__DeleteFile(struct soap *soap)
{	struct __ns1__DeleteFile soap_tmp___ns1__DeleteFile;
	struct ns1__DeleteFileResponse ns1__DeleteFileResponse;
	soap_default_ns1__DeleteFileResponse(soap, &ns1__DeleteFileResponse);
	soap_default___ns1__DeleteFile(soap, &soap_tmp___ns1__DeleteFile);
	if (!soap_get___ns1__DeleteFile(soap, &soap_tmp___ns1__DeleteFile, "-ns1:DeleteFile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__DeleteFile(soap, soap_tmp___ns1__DeleteFile.ns1__DeleteFile, &ns1__DeleteFileResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__DeleteFileResponse(soap, &ns1__DeleteFileResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__DeleteFileResponse(soap, &ns1__DeleteFileResponse, "ns1:DeleteFileResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__DeleteFileResponse(soap, &ns1__DeleteFileResponse, "ns1:DeleteFileResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetFile(struct soap *soap)
{	struct __ns1__GetFile soap_tmp___ns1__GetFile;
	struct ns1__GetFileResponse ns1__GetFileResponse;
	soap_default_ns1__GetFileResponse(soap, &ns1__GetFileResponse);
	soap_default___ns1__GetFile(soap, &soap_tmp___ns1__GetFile);
	if (!soap_get___ns1__GetFile(soap, &soap_tmp___ns1__GetFile, "-ns1:GetFile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetFile(soap, soap_tmp___ns1__GetFile.ns1__GetFile, &ns1__GetFileResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__GetFileResponse(soap, &ns1__GetFileResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__GetFileResponse(soap, &ns1__GetFileResponse, "ns1:GetFileResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__GetFileResponse(soap, &ns1__GetFileResponse, "ns1:GetFileResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREDecryptFile(struct soap *soap)
{	struct __ns1__SOF_USCOREDecryptFile soap_tmp___ns1__SOF_USCOREDecryptFile;
	struct ns1__SOF_USCOREDecryptFileResponse ns1__SOF_USCOREDecryptFileResponse;
	soap_default_ns1__SOF_USCOREDecryptFileResponse(soap, &ns1__SOF_USCOREDecryptFileResponse);
	soap_default___ns1__SOF_USCOREDecryptFile(soap, &soap_tmp___ns1__SOF_USCOREDecryptFile);
	if (!soap_get___ns1__SOF_USCOREDecryptFile(soap, &soap_tmp___ns1__SOF_USCOREDecryptFile, "-ns1:SOF_DecryptFile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREDecryptFile(soap, soap_tmp___ns1__SOF_USCOREDecryptFile.ns1__SOF_USCOREDecryptFile, &ns1__SOF_USCOREDecryptFileResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREDecryptFileResponse(soap, &ns1__SOF_USCOREDecryptFileResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREDecryptFileResponse(soap, &ns1__SOF_USCOREDecryptFileResponse, "ns1:SOF_DecryptFileResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREDecryptFileResponse(soap, &ns1__SOF_USCOREDecryptFileResponse, "ns1:SOF_DecryptFileResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORESetSignMethod(struct soap *soap)
{	struct __ns1__SOF_USCORESetSignMethod soap_tmp___ns1__SOF_USCORESetSignMethod;
	struct ns1__SOF_USCORESetSignMethodResponse ns1__SOF_USCORESetSignMethodResponse;
	soap_default_ns1__SOF_USCORESetSignMethodResponse(soap, &ns1__SOF_USCORESetSignMethodResponse);
	soap_default___ns1__SOF_USCORESetSignMethod(soap, &soap_tmp___ns1__SOF_USCORESetSignMethod);
	if (!soap_get___ns1__SOF_USCORESetSignMethod(soap, &soap_tmp___ns1__SOF_USCORESetSignMethod, "-ns1:SOF_SetSignMethod", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORESetSignMethod(soap, soap_tmp___ns1__SOF_USCORESetSignMethod.ns1__SOF_USCORESetSignMethod, &ns1__SOF_USCORESetSignMethodResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCORESetSignMethodResponse(soap, &ns1__SOF_USCORESetSignMethodResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCORESetSignMethodResponse(soap, &ns1__SOF_USCORESetSignMethodResponse, "ns1:SOF_SetSignMethodResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCORESetSignMethodResponse(soap, &ns1__SOF_USCORESetSignMethodResponse, "ns1:SOF_SetSignMethodResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGetTimeStampInfo(struct soap *soap)
{	struct __ns1__SOF_USCOREGetTimeStampInfo soap_tmp___ns1__SOF_USCOREGetTimeStampInfo;
	struct ns1__SOF_USCOREGetTimeStampInfoResponse ns1__SOF_USCOREGetTimeStampInfoResponse;
	soap_default_ns1__SOF_USCOREGetTimeStampInfoResponse(soap, &ns1__SOF_USCOREGetTimeStampInfoResponse);
	soap_default___ns1__SOF_USCOREGetTimeStampInfo(soap, &soap_tmp___ns1__SOF_USCOREGetTimeStampInfo);
	if (!soap_get___ns1__SOF_USCOREGetTimeStampInfo(soap, &soap_tmp___ns1__SOF_USCOREGetTimeStampInfo, "-ns1:SOF_GetTimeStampInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGetTimeStampInfo(soap, soap_tmp___ns1__SOF_USCOREGetTimeStampInfo.ns1__SOF_USCOREGetTimeStampInfo, &ns1__SOF_USCOREGetTimeStampInfoResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREGetTimeStampInfoResponse(soap, &ns1__SOF_USCOREGetTimeStampInfoResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREGetTimeStampInfoResponse(soap, &ns1__SOF_USCOREGetTimeStampInfoResponse, "ns1:SOF_GetTimeStampInfoResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREGetTimeStampInfoResponse(soap, &ns1__SOF_USCOREGetTimeStampInfoResponse, "ns1:SOF_GetTimeStampInfoResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREEncryptFile(struct soap *soap)
{	struct __ns1__SOF_USCOREEncryptFile soap_tmp___ns1__SOF_USCOREEncryptFile;
	struct ns1__SOF_USCOREEncryptFileResponse ns1__SOF_USCOREEncryptFileResponse;
	soap_default_ns1__SOF_USCOREEncryptFileResponse(soap, &ns1__SOF_USCOREEncryptFileResponse);
	soap_default___ns1__SOF_USCOREEncryptFile(soap, &soap_tmp___ns1__SOF_USCOREEncryptFile);
	if (!soap_get___ns1__SOF_USCOREEncryptFile(soap, &soap_tmp___ns1__SOF_USCOREEncryptFile, "-ns1:SOF_EncryptFile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREEncryptFile(soap, soap_tmp___ns1__SOF_USCOREEncryptFile.ns1__SOF_USCOREEncryptFile, &ns1__SOF_USCOREEncryptFileResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREEncryptFileResponse(soap, &ns1__SOF_USCOREEncryptFileResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREEncryptFileResponse(soap, &ns1__SOF_USCOREEncryptFileResponse, "ns1:SOF_EncryptFileResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREEncryptFileResponse(soap, &ns1__SOF_USCOREEncryptFileResponse, "ns1:SOF_EncryptFileResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORESignDataByP7(struct soap *soap)
{	struct __ns1__SOF_USCORESignDataByP7 soap_tmp___ns1__SOF_USCORESignDataByP7;
	struct ns1__SOF_USCORESignDataByP7Response ns1__SOF_USCORESignDataByP7Response;
	soap_default_ns1__SOF_USCORESignDataByP7Response(soap, &ns1__SOF_USCORESignDataByP7Response);
	soap_default___ns1__SOF_USCORESignDataByP7(soap, &soap_tmp___ns1__SOF_USCORESignDataByP7);
	if (!soap_get___ns1__SOF_USCORESignDataByP7(soap, &soap_tmp___ns1__SOF_USCORESignDataByP7, "-ns1:SOF_SignDataByP7", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORESignDataByP7(soap, soap_tmp___ns1__SOF_USCORESignDataByP7.ns1__SOF_USCORESignDataByP7, &ns1__SOF_USCORESignDataByP7Response);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCORESignDataByP7Response(soap, &ns1__SOF_USCORESignDataByP7Response);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCORESignDataByP7Response(soap, &ns1__SOF_USCORESignDataByP7Response, "ns1:SOF_SignDataByP7Response", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCORESignDataByP7Response(soap, &ns1__SOF_USCORESignDataByP7Response, "ns1:SOF_SignDataByP7Response", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREDecryptData(struct soap *soap)
{	struct __ns1__SOF_USCOREDecryptData soap_tmp___ns1__SOF_USCOREDecryptData;
	struct ns1__SOF_USCOREDecryptDataResponse ns1__SOF_USCOREDecryptDataResponse;
	soap_default_ns1__SOF_USCOREDecryptDataResponse(soap, &ns1__SOF_USCOREDecryptDataResponse);
	soap_default___ns1__SOF_USCOREDecryptData(soap, &soap_tmp___ns1__SOF_USCOREDecryptData);
	if (!soap_get___ns1__SOF_USCOREDecryptData(soap, &soap_tmp___ns1__SOF_USCOREDecryptData, "-ns1:SOF_DecryptData", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREDecryptData(soap, soap_tmp___ns1__SOF_USCOREDecryptData.ns1__SOF_USCOREDecryptData, &ns1__SOF_USCOREDecryptDataResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREDecryptDataResponse(soap, &ns1__SOF_USCOREDecryptDataResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREDecryptDataResponse(soap, &ns1__SOF_USCOREDecryptDataResponse, "ns1:SOF_DecryptDataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREDecryptDataResponse(soap, &ns1__SOF_USCOREDecryptDataResponse, "ns1:SOF_DecryptDataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORESignDataXML(struct soap *soap)
{	struct __ns1__SOF_USCORESignDataXML soap_tmp___ns1__SOF_USCORESignDataXML;
	struct ns1__SOF_USCORESignDataXMLResponse ns1__SOF_USCORESignDataXMLResponse;
	soap_default_ns1__SOF_USCORESignDataXMLResponse(soap, &ns1__SOF_USCORESignDataXMLResponse);
	soap_default___ns1__SOF_USCORESignDataXML(soap, &soap_tmp___ns1__SOF_USCORESignDataXML);
	if (!soap_get___ns1__SOF_USCORESignDataXML(soap, &soap_tmp___ns1__SOF_USCORESignDataXML, "-ns1:SOF_SignDataXML", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORESignDataXML(soap, soap_tmp___ns1__SOF_USCORESignDataXML.ns1__SOF_USCORESignDataXML, &ns1__SOF_USCORESignDataXMLResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCORESignDataXMLResponse(soap, &ns1__SOF_USCORESignDataXMLResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCORESignDataXMLResponse(soap, &ns1__SOF_USCORESignDataXMLResponse, "ns1:SOF_SignDataXMLResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCORESignDataXMLResponse(soap, &ns1__SOF_USCORESignDataXMLResponse, "ns1:SOF_SignDataXMLResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGetCertInfo(struct soap *soap)
{	struct __ns1__SOF_USCOREGetCertInfo soap_tmp___ns1__SOF_USCOREGetCertInfo;
	struct ns1__SOF_USCOREGetCertInfoResponse ns1__SOF_USCOREGetCertInfoResponse;
	soap_default_ns1__SOF_USCOREGetCertInfoResponse(soap, &ns1__SOF_USCOREGetCertInfoResponse);
	soap_default___ns1__SOF_USCOREGetCertInfo(soap, &soap_tmp___ns1__SOF_USCOREGetCertInfo);
	if (!soap_get___ns1__SOF_USCOREGetCertInfo(soap, &soap_tmp___ns1__SOF_USCOREGetCertInfo, "-ns1:SOF_GetCertInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGetCertInfo(soap, soap_tmp___ns1__SOF_USCOREGetCertInfo.ns1__SOF_USCOREGetCertInfo, &ns1__SOF_USCOREGetCertInfoResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREGetCertInfoResponse(soap, &ns1__SOF_USCOREGetCertInfoResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREGetCertInfoResponse(soap, &ns1__SOF_USCOREGetCertInfoResponse, "ns1:SOF_GetCertInfoResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREGetCertInfoResponse(soap, &ns1__SOF_USCOREGetCertInfoResponse, "ns1:SOF_GetCertInfoResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREQueryCertTrustListAltNames(struct soap *soap)
{	struct __ns1__SOF_USCOREQueryCertTrustListAltNames soap_tmp___ns1__SOF_USCOREQueryCertTrustListAltNames;
	struct ns1__SOF_USCOREQueryCertTrustListAltNamesResponse ns1__SOF_USCOREQueryCertTrustListAltNamesResponse;
	soap_default_ns1__SOF_USCOREQueryCertTrustListAltNamesResponse(soap, &ns1__SOF_USCOREQueryCertTrustListAltNamesResponse);
	soap_default___ns1__SOF_USCOREQueryCertTrustListAltNames(soap, &soap_tmp___ns1__SOF_USCOREQueryCertTrustListAltNames);
	if (!soap_get___ns1__SOF_USCOREQueryCertTrustListAltNames(soap, &soap_tmp___ns1__SOF_USCOREQueryCertTrustListAltNames, "-ns1:SOF_QueryCertTrustListAltNames", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREQueryCertTrustListAltNames(soap, soap_tmp___ns1__SOF_USCOREQueryCertTrustListAltNames.ns1__SOF_USCOREQueryCertTrustListAltNames, &ns1__SOF_USCOREQueryCertTrustListAltNamesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREQueryCertTrustListAltNamesResponse(soap, &ns1__SOF_USCOREQueryCertTrustListAltNamesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREQueryCertTrustListAltNamesResponse(soap, &ns1__SOF_USCOREQueryCertTrustListAltNamesResponse, "ns1:SOF_QueryCertTrustListAltNamesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREQueryCertTrustListAltNamesResponse(soap, &ns1__SOF_USCOREQueryCertTrustListAltNamesResponse, "ns1:SOF_QueryCertTrustListAltNamesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREEncryptData(struct soap *soap)
{	struct __ns1__SOF_USCOREEncryptData soap_tmp___ns1__SOF_USCOREEncryptData;
	struct ns1__SOF_USCOREEncryptDataResponse ns1__SOF_USCOREEncryptDataResponse;
	soap_default_ns1__SOF_USCOREEncryptDataResponse(soap, &ns1__SOF_USCOREEncryptDataResponse);
	soap_default___ns1__SOF_USCOREEncryptData(soap, &soap_tmp___ns1__SOF_USCOREEncryptData);
	if (!soap_get___ns1__SOF_USCOREEncryptData(soap, &soap_tmp___ns1__SOF_USCOREEncryptData, "-ns1:SOF_EncryptData", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREEncryptData(soap, soap_tmp___ns1__SOF_USCOREEncryptData.ns1__SOF_USCOREEncryptData, &ns1__SOF_USCOREEncryptDataResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__SOF_USCOREEncryptDataResponse(soap, &ns1__SOF_USCOREEncryptDataResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SOF_USCOREEncryptDataResponse(soap, &ns1__SOF_USCOREEncryptDataResponse, "ns1:SOF_EncryptDataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SOF_USCOREEncryptDataResponse(soap, &ns1__SOF_USCOREEncryptDataResponse, "ns1:SOF_EncryptDataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
