/* soapClient.c
   Generated by gSOAP 2.8.44 for SOF_interface.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.44 2017-06-07 10:36:53 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREVerifySignedData(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREVerifySignedData *ns1__SOF_USCOREVerifySignedData, struct ns1__SOF_USCOREVerifySignedDataResponse *ns1__SOF_USCOREVerifySignedDataResponse)
{	struct __ns1__SOF_USCOREVerifySignedData soap_tmp___ns1__SOF_USCOREVerifySignedData;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREVerifySignedData.ns1__SOF_USCOREVerifySignedData = ns1__SOF_USCOREVerifySignedData;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREVerifySignedData(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedData);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREVerifySignedData(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedData, "-ns1:SOF_VerifySignedData", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREVerifySignedData(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedData, "-ns1:SOF_VerifySignedData", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREVerifySignedDataResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREVerifySignedDataResponse(soap, ns1__SOF_USCOREVerifySignedDataResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREVerifySignedDataResponse(soap, ns1__SOF_USCOREVerifySignedDataResponse, "ns1:SOF_VerifySignedDataResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREQueryCertTrustList(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREQueryCertTrustList *ns1__SOF_USCOREQueryCertTrustList, struct ns1__SOF_USCOREQueryCertTrustListResponse *ns1__SOF_USCOREQueryCertTrustListResponse)
{	struct __ns1__SOF_USCOREQueryCertTrustList soap_tmp___ns1__SOF_USCOREQueryCertTrustList;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREQueryCertTrustList.ns1__SOF_USCOREQueryCertTrustList = ns1__SOF_USCOREQueryCertTrustList;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREQueryCertTrustList(soap, &soap_tmp___ns1__SOF_USCOREQueryCertTrustList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREQueryCertTrustList(soap, &soap_tmp___ns1__SOF_USCOREQueryCertTrustList, "-ns1:SOF_QueryCertTrustList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREQueryCertTrustList(soap, &soap_tmp___ns1__SOF_USCOREQueryCertTrustList, "-ns1:SOF_QueryCertTrustList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREQueryCertTrustListResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREQueryCertTrustListResponse(soap, ns1__SOF_USCOREQueryCertTrustListResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREQueryCertTrustListResponse(soap, ns1__SOF_USCOREQueryCertTrustListResponse, "ns1:SOF_QueryCertTrustListResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREGetP7SignDataInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREGetP7SignDataInfo *ns1__SOF_USCOREGetP7SignDataInfo, struct ns1__SOF_USCOREGetP7SignDataInfoResponse *ns1__SOF_USCOREGetP7SignDataInfoResponse)
{	struct __ns1__SOF_USCOREGetP7SignDataInfo soap_tmp___ns1__SOF_USCOREGetP7SignDataInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREGetP7SignDataInfo.ns1__SOF_USCOREGetP7SignDataInfo = ns1__SOF_USCOREGetP7SignDataInfo;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREGetP7SignDataInfo(soap, &soap_tmp___ns1__SOF_USCOREGetP7SignDataInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREGetP7SignDataInfo(soap, &soap_tmp___ns1__SOF_USCOREGetP7SignDataInfo, "-ns1:SOF_GetP7SignDataInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREGetP7SignDataInfo(soap, &soap_tmp___ns1__SOF_USCOREGetP7SignDataInfo, "-ns1:SOF_GetP7SignDataInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREGetP7SignDataInfoResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREGetP7SignDataInfoResponse(soap, ns1__SOF_USCOREGetP7SignDataInfoResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREGetP7SignDataInfoResponse(soap, ns1__SOF_USCOREGetP7SignDataInfoResponse, "ns1:SOF_GetP7SignDataInfoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCORESetCertTrustList(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCORESetCertTrustList *ns1__SOF_USCORESetCertTrustList, struct ns1__SOF_USCORESetCertTrustListResponse *ns1__SOF_USCORESetCertTrustListResponse)
{	struct __ns1__SOF_USCORESetCertTrustList soap_tmp___ns1__SOF_USCORESetCertTrustList;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCORESetCertTrustList.ns1__SOF_USCORESetCertTrustList = ns1__SOF_USCORESetCertTrustList;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCORESetCertTrustList(soap, &soap_tmp___ns1__SOF_USCORESetCertTrustList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCORESetCertTrustList(soap, &soap_tmp___ns1__SOF_USCORESetCertTrustList, "-ns1:SOF_SetCertTrustList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCORESetCertTrustList(soap, &soap_tmp___ns1__SOF_USCORESetCertTrustList, "-ns1:SOF_SetCertTrustList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCORESetCertTrustListResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCORESetCertTrustListResponse(soap, ns1__SOF_USCORESetCertTrustListResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCORESetCertTrustListResponse(soap, ns1__SOF_USCORESetCertTrustListResponse, "ns1:SOF_SetCertTrustListResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREVerifySignedDataByP7(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREVerifySignedDataByP7 *ns1__SOF_USCOREVerifySignedDataByP7, struct ns1__SOF_USCOREVerifySignedDataByP7Response *ns1__SOF_USCOREVerifySignedDataByP7Response)
{	struct __ns1__SOF_USCOREVerifySignedDataByP7 soap_tmp___ns1__SOF_USCOREVerifySignedDataByP7;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREVerifySignedDataByP7.ns1__SOF_USCOREVerifySignedDataByP7 = ns1__SOF_USCOREVerifySignedDataByP7;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREVerifySignedDataByP7(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedDataByP7);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREVerifySignedDataByP7(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedDataByP7, "-ns1:SOF_VerifySignedDataByP7", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREVerifySignedDataByP7(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedDataByP7, "-ns1:SOF_VerifySignedDataByP7", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREVerifySignedDataByP7Response)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREVerifySignedDataByP7Response(soap, ns1__SOF_USCOREVerifySignedDataByP7Response);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREVerifySignedDataByP7Response(soap, ns1__SOF_USCOREVerifySignedDataByP7Response, "ns1:SOF_VerifySignedDataByP7Response", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREPubKeyEncrypt(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREPubKeyEncrypt *ns1__SOF_USCOREPubKeyEncrypt, struct ns1__SOF_USCOREPubKeyEncryptResponse *ns1__SOF_USCOREPubKeyEncryptResponse)
{	struct __ns1__SOF_USCOREPubKeyEncrypt soap_tmp___ns1__SOF_USCOREPubKeyEncrypt;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREPubKeyEncrypt.ns1__SOF_USCOREPubKeyEncrypt = ns1__SOF_USCOREPubKeyEncrypt;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREPubKeyEncrypt(soap, &soap_tmp___ns1__SOF_USCOREPubKeyEncrypt);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREPubKeyEncrypt(soap, &soap_tmp___ns1__SOF_USCOREPubKeyEncrypt, "-ns1:SOF_PubKeyEncrypt", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREPubKeyEncrypt(soap, &soap_tmp___ns1__SOF_USCOREPubKeyEncrypt, "-ns1:SOF_PubKeyEncrypt", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREPubKeyEncryptResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREPubKeyEncryptResponse(soap, ns1__SOF_USCOREPubKeyEncryptResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREPubKeyEncryptResponse(soap, ns1__SOF_USCOREPubKeyEncryptResponse, "ns1:SOF_PubKeyEncryptResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREVerifyTimeStamp(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREVerifyTimeStamp *ns1__SOF_USCOREVerifyTimeStamp, struct ns1__SOF_USCOREVerifyTimeStampResponse *ns1__SOF_USCOREVerifyTimeStampResponse)
{	struct __ns1__SOF_USCOREVerifyTimeStamp soap_tmp___ns1__SOF_USCOREVerifyTimeStamp;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREVerifyTimeStamp.ns1__SOF_USCOREVerifyTimeStamp = ns1__SOF_USCOREVerifyTimeStamp;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREVerifyTimeStamp(soap, &soap_tmp___ns1__SOF_USCOREVerifyTimeStamp);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREVerifyTimeStamp(soap, &soap_tmp___ns1__SOF_USCOREVerifyTimeStamp, "-ns1:SOF_VerifyTimeStamp", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREVerifyTimeStamp(soap, &soap_tmp___ns1__SOF_USCOREVerifyTimeStamp, "-ns1:SOF_VerifyTimeStamp", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREVerifyTimeStampResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREVerifyTimeStampResponse(soap, ns1__SOF_USCOREVerifyTimeStampResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREVerifyTimeStampResponse(soap, ns1__SOF_USCOREVerifyTimeStampResponse, "ns1:SOF_VerifyTimeStampResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREVerifySignedFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREVerifySignedFile *ns1__SOF_USCOREVerifySignedFile, struct ns1__SOF_USCOREVerifySignedFileResponse *ns1__SOF_USCOREVerifySignedFileResponse)
{	struct __ns1__SOF_USCOREVerifySignedFile soap_tmp___ns1__SOF_USCOREVerifySignedFile;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREVerifySignedFile.ns1__SOF_USCOREVerifySignedFile = ns1__SOF_USCOREVerifySignedFile;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREVerifySignedFile(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedFile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREVerifySignedFile(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedFile, "-ns1:SOF_VerifySignedFile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREVerifySignedFile(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedFile, "-ns1:SOF_VerifySignedFile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREVerifySignedFileResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREVerifySignedFileResponse(soap, ns1__SOF_USCOREVerifySignedFileResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREVerifySignedFileResponse(soap, ns1__SOF_USCOREVerifySignedFileResponse, "ns1:SOF_VerifySignedFileResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREGetCertInfoByOid(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREGetCertInfoByOid *ns1__SOF_USCOREGetCertInfoByOid, struct ns1__SOF_USCOREGetCertInfoByOidResponse *ns1__SOF_USCOREGetCertInfoByOidResponse)
{	struct __ns1__SOF_USCOREGetCertInfoByOid soap_tmp___ns1__SOF_USCOREGetCertInfoByOid;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREGetCertInfoByOid.ns1__SOF_USCOREGetCertInfoByOid = ns1__SOF_USCOREGetCertInfoByOid;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREGetCertInfoByOid(soap, &soap_tmp___ns1__SOF_USCOREGetCertInfoByOid);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREGetCertInfoByOid(soap, &soap_tmp___ns1__SOF_USCOREGetCertInfoByOid, "-ns1:SOF_GetCertInfoByOid", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREGetCertInfoByOid(soap, &soap_tmp___ns1__SOF_USCOREGetCertInfoByOid, "-ns1:SOF_GetCertInfoByOid", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREGetCertInfoByOidResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREGetCertInfoByOidResponse(soap, ns1__SOF_USCOREGetCertInfoByOidResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREGetCertInfoByOidResponse(soap, ns1__SOF_USCOREGetCertInfoByOidResponse, "ns1:SOF_GetCertInfoByOidResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREGetServerCertificate(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREGetServerCertificate *ns1__SOF_USCOREGetServerCertificate, struct ns1__SOF_USCOREGetServerCertificateResponse *ns1__SOF_USCOREGetServerCertificateResponse)
{	struct __ns1__SOF_USCOREGetServerCertificate soap_tmp___ns1__SOF_USCOREGetServerCertificate;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREGetServerCertificate.ns1__SOF_USCOREGetServerCertificate = ns1__SOF_USCOREGetServerCertificate;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREGetServerCertificate(soap, &soap_tmp___ns1__SOF_USCOREGetServerCertificate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREGetServerCertificate(soap, &soap_tmp___ns1__SOF_USCOREGetServerCertificate, "-ns1:SOF_GetServerCertificate", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREGetServerCertificate(soap, &soap_tmp___ns1__SOF_USCOREGetServerCertificate, "-ns1:SOF_GetServerCertificate", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREGetServerCertificateResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREGetServerCertificateResponse(soap, ns1__SOF_USCOREGetServerCertificateResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREGetServerCertificateResponse(soap, ns1__SOF_USCOREGetServerCertificateResponse, "ns1:SOF_GetServerCertificateResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREDelCertTrustList(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREDelCertTrustList *ns1__SOF_USCOREDelCertTrustList, struct ns1__SOF_USCOREDelCertTrustListResponse *ns1__SOF_USCOREDelCertTrustListResponse)
{	struct __ns1__SOF_USCOREDelCertTrustList soap_tmp___ns1__SOF_USCOREDelCertTrustList;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREDelCertTrustList.ns1__SOF_USCOREDelCertTrustList = ns1__SOF_USCOREDelCertTrustList;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREDelCertTrustList(soap, &soap_tmp___ns1__SOF_USCOREDelCertTrustList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREDelCertTrustList(soap, &soap_tmp___ns1__SOF_USCOREDelCertTrustList, "-ns1:SOF_DelCertTrustList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREDelCertTrustList(soap, &soap_tmp___ns1__SOF_USCOREDelCertTrustList, "-ns1:SOF_DelCertTrustList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREDelCertTrustListResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREDelCertTrustListResponse(soap, ns1__SOF_USCOREDelCertTrustListResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREDelCertTrustListResponse(soap, ns1__SOF_USCOREDelCertTrustListResponse, "ns1:SOF_DelCertTrustListResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREGetXMLSignatureInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREGetXMLSignatureInfo *ns1__SOF_USCOREGetXMLSignatureInfo, struct ns1__SOF_USCOREGetXMLSignatureInfoResponse *ns1__SOF_USCOREGetXMLSignatureInfoResponse)
{	struct __ns1__SOF_USCOREGetXMLSignatureInfo soap_tmp___ns1__SOF_USCOREGetXMLSignatureInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREGetXMLSignatureInfo.ns1__SOF_USCOREGetXMLSignatureInfo = ns1__SOF_USCOREGetXMLSignatureInfo;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREGetXMLSignatureInfo(soap, &soap_tmp___ns1__SOF_USCOREGetXMLSignatureInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREGetXMLSignatureInfo(soap, &soap_tmp___ns1__SOF_USCOREGetXMLSignatureInfo, "-ns1:SOF_GetXMLSignatureInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREGetXMLSignatureInfo(soap, &soap_tmp___ns1__SOF_USCOREGetXMLSignatureInfo, "-ns1:SOF_GetXMLSignatureInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREGetXMLSignatureInfoResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREGetXMLSignatureInfoResponse(soap, ns1__SOF_USCOREGetXMLSignatureInfoResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREGetXMLSignatureInfoResponse(soap, ns1__SOF_USCOREGetXMLSignatureInfoResponse, "ns1:SOF_GetXMLSignatureInfoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCORESignData(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCORESignData *ns1__SOF_USCORESignData, struct ns1__SOF_USCORESignDataResponse *ns1__SOF_USCORESignDataResponse)
{	struct __ns1__SOF_USCORESignData soap_tmp___ns1__SOF_USCORESignData;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCORESignData.ns1__SOF_USCORESignData = ns1__SOF_USCORESignData;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCORESignData(soap, &soap_tmp___ns1__SOF_USCORESignData);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCORESignData(soap, &soap_tmp___ns1__SOF_USCORESignData, "-ns1:SOF_SignData", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCORESignData(soap, &soap_tmp___ns1__SOF_USCORESignData, "-ns1:SOF_SignData", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCORESignDataResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCORESignDataResponse(soap, ns1__SOF_USCORESignDataResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCORESignDataResponse(soap, ns1__SOF_USCORESignDataResponse, "ns1:SOF_SignDataResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREVerifySignedDataXML(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREVerifySignedDataXML *ns1__SOF_USCOREVerifySignedDataXML, struct ns1__SOF_USCOREVerifySignedDataXMLResponse *ns1__SOF_USCOREVerifySignedDataXMLResponse)
{	struct __ns1__SOF_USCOREVerifySignedDataXML soap_tmp___ns1__SOF_USCOREVerifySignedDataXML;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREVerifySignedDataXML.ns1__SOF_USCOREVerifySignedDataXML = ns1__SOF_USCOREVerifySignedDataXML;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREVerifySignedDataXML(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedDataXML);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREVerifySignedDataXML(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedDataXML, "-ns1:SOF_VerifySignedDataXML", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREVerifySignedDataXML(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedDataXML, "-ns1:SOF_VerifySignedDataXML", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREVerifySignedDataXMLResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREVerifySignedDataXMLResponse(soap, ns1__SOF_USCOREVerifySignedDataXMLResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREVerifySignedDataXMLResponse(soap, ns1__SOF_USCOREVerifySignedDataXMLResponse, "ns1:SOF_VerifySignedDataXMLResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCORESignFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCORESignFile *ns1__SOF_USCORESignFile, struct ns1__SOF_USCORESignFileResponse *ns1__SOF_USCORESignFileResponse)
{	struct __ns1__SOF_USCORESignFile soap_tmp___ns1__SOF_USCORESignFile;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCORESignFile.ns1__SOF_USCORESignFile = ns1__SOF_USCORESignFile;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCORESignFile(soap, &soap_tmp___ns1__SOF_USCORESignFile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCORESignFile(soap, &soap_tmp___ns1__SOF_USCORESignFile, "-ns1:SOF_SignFile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCORESignFile(soap, &soap_tmp___ns1__SOF_USCORESignFile, "-ns1:SOF_SignFile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCORESignFileResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCORESignFileResponse(soap, ns1__SOF_USCORESignFileResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCORESignFileResponse(soap, ns1__SOF_USCORESignFileResponse, "ns1:SOF_SignFileResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREGetInstance(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREGetInstance *ns1__SOF_USCOREGetInstance, struct ns1__SOF_USCOREGetInstanceResponse *ns1__SOF_USCOREGetInstanceResponse)
{	struct __ns1__SOF_USCOREGetInstance soap_tmp___ns1__SOF_USCOREGetInstance;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREGetInstance.ns1__SOF_USCOREGetInstance = ns1__SOF_USCOREGetInstance;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREGetInstance(soap, &soap_tmp___ns1__SOF_USCOREGetInstance);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREGetInstance(soap, &soap_tmp___ns1__SOF_USCOREGetInstance, "-ns1:SOF_GetInstance", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREGetInstance(soap, &soap_tmp___ns1__SOF_USCOREGetInstance, "-ns1:SOF_GetInstance", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREGetInstanceResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREGetInstanceResponse(soap, ns1__SOF_USCOREGetInstanceResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREGetInstanceResponse(soap, ns1__SOF_USCOREGetInstanceResponse, "ns1:SOF_GetInstanceResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREPriKeyDecrypt(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREPriKeyDecrypt *ns1__SOF_USCOREPriKeyDecrypt, struct ns1__SOF_USCOREPriKeyDecryptResponse *ns1__SOF_USCOREPriKeyDecryptResponse)
{	struct __ns1__SOF_USCOREPriKeyDecrypt soap_tmp___ns1__SOF_USCOREPriKeyDecrypt;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREPriKeyDecrypt.ns1__SOF_USCOREPriKeyDecrypt = ns1__SOF_USCOREPriKeyDecrypt;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREPriKeyDecrypt(soap, &soap_tmp___ns1__SOF_USCOREPriKeyDecrypt);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREPriKeyDecrypt(soap, &soap_tmp___ns1__SOF_USCOREPriKeyDecrypt, "-ns1:SOF_PriKeyDecrypt", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREPriKeyDecrypt(soap, &soap_tmp___ns1__SOF_USCOREPriKeyDecrypt, "-ns1:SOF_PriKeyDecrypt", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREPriKeyDecryptResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREPriKeyDecryptResponse(soap, ns1__SOF_USCOREPriKeyDecryptResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREPriKeyDecryptResponse(soap, ns1__SOF_USCOREPriKeyDecryptResponse, "ns1:SOF_PriKeyDecryptResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREGenRandom(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREGenRandom *ns1__SOF_USCOREGenRandom, struct ns1__SOF_USCOREGenRandomResponse *ns1__SOF_USCOREGenRandomResponse)
{	struct __ns1__SOF_USCOREGenRandom soap_tmp___ns1__SOF_USCOREGenRandom;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREGenRandom.ns1__SOF_USCOREGenRandom = ns1__SOF_USCOREGenRandom;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREGenRandom(soap, &soap_tmp___ns1__SOF_USCOREGenRandom);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREGenRandom(soap, &soap_tmp___ns1__SOF_USCOREGenRandom, "-ns1:SOF_GenRandom", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREGenRandom(soap, &soap_tmp___ns1__SOF_USCOREGenRandom, "-ns1:SOF_GenRandom", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREGenRandomResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREGenRandomResponse(soap, ns1__SOF_USCOREGenRandomResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREGenRandomResponse(soap, ns1__SOF_USCOREGenRandomResponse, "ns1:SOF_GenRandomResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREGetSignMethod(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREGetSignMethod *ns1__SOF_USCOREGetSignMethod, struct ns1__SOF_USCOREGetSignMethodResponse *ns1__SOF_USCOREGetSignMethodResponse)
{	struct __ns1__SOF_USCOREGetSignMethod soap_tmp___ns1__SOF_USCOREGetSignMethod;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREGetSignMethod.ns1__SOF_USCOREGetSignMethod = ns1__SOF_USCOREGetSignMethod;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREGetSignMethod(soap, &soap_tmp___ns1__SOF_USCOREGetSignMethod);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREGetSignMethod(soap, &soap_tmp___ns1__SOF_USCOREGetSignMethod, "-ns1:SOF_GetSignMethod", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREGetSignMethod(soap, &soap_tmp___ns1__SOF_USCOREGetSignMethod, "-ns1:SOF_GetSignMethod", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREGetSignMethodResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREGetSignMethodResponse(soap, ns1__SOF_USCOREGetSignMethodResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREGetSignMethodResponse(soap, ns1__SOF_USCOREGetSignMethodResponse, "ns1:SOF_GetSignMethodResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCORESetWebAppName(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCORESetWebAppName *ns1__SOF_USCORESetWebAppName, struct ns1__SOF_USCORESetWebAppNameResponse *ns1__SOF_USCORESetWebAppNameResponse)
{	struct __ns1__SOF_USCORESetWebAppName soap_tmp___ns1__SOF_USCORESetWebAppName;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCORESetWebAppName.ns1__SOF_USCORESetWebAppName = ns1__SOF_USCORESetWebAppName;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCORESetWebAppName(soap, &soap_tmp___ns1__SOF_USCORESetWebAppName);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCORESetWebAppName(soap, &soap_tmp___ns1__SOF_USCORESetWebAppName, "-ns1:SOF_SetWebAppName", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCORESetWebAppName(soap, &soap_tmp___ns1__SOF_USCORESetWebAppName, "-ns1:SOF_SetWebAppName", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCORESetWebAppNameResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCORESetWebAppNameResponse(soap, ns1__SOF_USCORESetWebAppNameResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCORESetWebAppNameResponse(soap, ns1__SOF_USCORESetWebAppNameResponse, "ns1:SOF_SetWebAppNameResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCORESetEncryptMethod(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCORESetEncryptMethod *ns1__SOF_USCORESetEncryptMethod, struct ns1__SOF_USCORESetEncryptMethodResponse *ns1__SOF_USCORESetEncryptMethodResponse)
{	struct __ns1__SOF_USCORESetEncryptMethod soap_tmp___ns1__SOF_USCORESetEncryptMethod;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCORESetEncryptMethod.ns1__SOF_USCORESetEncryptMethod = ns1__SOF_USCORESetEncryptMethod;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCORESetEncryptMethod(soap, &soap_tmp___ns1__SOF_USCORESetEncryptMethod);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCORESetEncryptMethod(soap, &soap_tmp___ns1__SOF_USCORESetEncryptMethod, "-ns1:SOF_SetEncryptMethod", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCORESetEncryptMethod(soap, &soap_tmp___ns1__SOF_USCORESetEncryptMethod, "-ns1:SOF_SetEncryptMethod", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCORESetEncryptMethodResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCORESetEncryptMethodResponse(soap, ns1__SOF_USCORESetEncryptMethodResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCORESetEncryptMethodResponse(soap, ns1__SOF_USCORESetEncryptMethodResponse, "ns1:SOF_SetEncryptMethodResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCORECreateTimeStampRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCORECreateTimeStampRequest *ns1__SOF_USCORECreateTimeStampRequest, struct ns1__SOF_USCORECreateTimeStampRequestResponse *ns1__SOF_USCORECreateTimeStampRequestResponse)
{	struct __ns1__SOF_USCORECreateTimeStampRequest soap_tmp___ns1__SOF_USCORECreateTimeStampRequest;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCORECreateTimeStampRequest.ns1__SOF_USCORECreateTimeStampRequest = ns1__SOF_USCORECreateTimeStampRequest;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCORECreateTimeStampRequest(soap, &soap_tmp___ns1__SOF_USCORECreateTimeStampRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCORECreateTimeStampRequest(soap, &soap_tmp___ns1__SOF_USCORECreateTimeStampRequest, "-ns1:SOF_CreateTimeStampRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCORECreateTimeStampRequest(soap, &soap_tmp___ns1__SOF_USCORECreateTimeStampRequest, "-ns1:SOF_CreateTimeStampRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCORECreateTimeStampRequestResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCORECreateTimeStampRequestResponse(soap, ns1__SOF_USCORECreateTimeStampRequestResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCORECreateTimeStampRequestResponse(soap, ns1__SOF_USCORECreateTimeStampRequestResponse, "ns1:SOF_CreateTimeStampRequestResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREGetEncryptMethod(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREGetEncryptMethod *ns1__SOF_USCOREGetEncryptMethod, struct ns1__SOF_USCOREGetEncryptMethodResponse *ns1__SOF_USCOREGetEncryptMethodResponse)
{	struct __ns1__SOF_USCOREGetEncryptMethod soap_tmp___ns1__SOF_USCOREGetEncryptMethod;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREGetEncryptMethod.ns1__SOF_USCOREGetEncryptMethod = ns1__SOF_USCOREGetEncryptMethod;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREGetEncryptMethod(soap, &soap_tmp___ns1__SOF_USCOREGetEncryptMethod);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREGetEncryptMethod(soap, &soap_tmp___ns1__SOF_USCOREGetEncryptMethod, "-ns1:SOF_GetEncryptMethod", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREGetEncryptMethod(soap, &soap_tmp___ns1__SOF_USCOREGetEncryptMethod, "-ns1:SOF_GetEncryptMethod", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREGetEncryptMethodResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREGetEncryptMethodResponse(soap, ns1__SOF_USCOREGetEncryptMethodResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREGetEncryptMethodResponse(soap, ns1__SOF_USCOREGetEncryptMethodResponse, "ns1:SOF_GetEncryptMethodResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCORECreateTimeStampResponse(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCORECreateTimeStampResponse *ns1__SOF_USCORECreateTimeStampResponse, struct ns1__SOF_USCORECreateTimeStampResponseResponse *ns1__SOF_USCORECreateTimeStampResponseResponse)
{	struct __ns1__SOF_USCORECreateTimeStampResponse soap_tmp___ns1__SOF_USCORECreateTimeStampResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCORECreateTimeStampResponse.ns1__SOF_USCORECreateTimeStampResponse = ns1__SOF_USCORECreateTimeStampResponse;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCORECreateTimeStampResponse(soap, &soap_tmp___ns1__SOF_USCORECreateTimeStampResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCORECreateTimeStampResponse(soap, &soap_tmp___ns1__SOF_USCORECreateTimeStampResponse, "-ns1:SOF_CreateTimeStampResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCORECreateTimeStampResponse(soap, &soap_tmp___ns1__SOF_USCORECreateTimeStampResponse, "-ns1:SOF_CreateTimeStampResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCORECreateTimeStampResponseResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCORECreateTimeStampResponseResponse(soap, ns1__SOF_USCORECreateTimeStampResponseResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCORECreateTimeStampResponseResponse(soap, ns1__SOF_USCORECreateTimeStampResponseResponse, "ns1:SOF_CreateTimeStampResponseResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREValidateCert(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREValidateCert *ns1__SOF_USCOREValidateCert, struct ns1__SOF_USCOREValidateCertResponse *ns1__SOF_USCOREValidateCertResponse)
{	struct __ns1__SOF_USCOREValidateCert soap_tmp___ns1__SOF_USCOREValidateCert;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREValidateCert.ns1__SOF_USCOREValidateCert = ns1__SOF_USCOREValidateCert;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREValidateCert(soap, &soap_tmp___ns1__SOF_USCOREValidateCert);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREValidateCert(soap, &soap_tmp___ns1__SOF_USCOREValidateCert, "-ns1:SOF_ValidateCert", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREValidateCert(soap, &soap_tmp___ns1__SOF_USCOREValidateCert, "-ns1:SOF_ValidateCert", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREValidateCertResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREValidateCertResponse(soap, ns1__SOF_USCOREValidateCertResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREValidateCertResponse(soap, ns1__SOF_USCOREValidateCertResponse, "ns1:SOF_ValidateCertResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__DeleteFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__DeleteFile *ns1__DeleteFile, struct ns1__DeleteFileResponse *ns1__DeleteFileResponse)
{	struct __ns1__DeleteFile soap_tmp___ns1__DeleteFile;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__DeleteFile.ns1__DeleteFile = ns1__DeleteFile;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__DeleteFile(soap, &soap_tmp___ns1__DeleteFile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__DeleteFile(soap, &soap_tmp___ns1__DeleteFile, "-ns1:DeleteFile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__DeleteFile(soap, &soap_tmp___ns1__DeleteFile, "-ns1:DeleteFile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__DeleteFileResponse)
		return soap_closesock(soap);
	soap_default_ns1__DeleteFileResponse(soap, ns1__DeleteFileResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__DeleteFileResponse(soap, ns1__DeleteFileResponse, "ns1:DeleteFileResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__GetFile *ns1__GetFile, struct ns1__GetFileResponse *ns1__GetFileResponse)
{	struct __ns1__GetFile soap_tmp___ns1__GetFile;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__GetFile.ns1__GetFile = ns1__GetFile;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetFile(soap, &soap_tmp___ns1__GetFile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetFile(soap, &soap_tmp___ns1__GetFile, "-ns1:GetFile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetFile(soap, &soap_tmp___ns1__GetFile, "-ns1:GetFile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetFileResponse)
		return soap_closesock(soap);
	soap_default_ns1__GetFileResponse(soap, ns1__GetFileResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__GetFileResponse(soap, ns1__GetFileResponse, "ns1:GetFileResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREDecryptFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREDecryptFile *ns1__SOF_USCOREDecryptFile, struct ns1__SOF_USCOREDecryptFileResponse *ns1__SOF_USCOREDecryptFileResponse)
{	struct __ns1__SOF_USCOREDecryptFile soap_tmp___ns1__SOF_USCOREDecryptFile;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREDecryptFile.ns1__SOF_USCOREDecryptFile = ns1__SOF_USCOREDecryptFile;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREDecryptFile(soap, &soap_tmp___ns1__SOF_USCOREDecryptFile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREDecryptFile(soap, &soap_tmp___ns1__SOF_USCOREDecryptFile, "-ns1:SOF_DecryptFile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREDecryptFile(soap, &soap_tmp___ns1__SOF_USCOREDecryptFile, "-ns1:SOF_DecryptFile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREDecryptFileResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREDecryptFileResponse(soap, ns1__SOF_USCOREDecryptFileResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREDecryptFileResponse(soap, ns1__SOF_USCOREDecryptFileResponse, "ns1:SOF_DecryptFileResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCORESetSignMethod(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCORESetSignMethod *ns1__SOF_USCORESetSignMethod, struct ns1__SOF_USCORESetSignMethodResponse *ns1__SOF_USCORESetSignMethodResponse)
{	struct __ns1__SOF_USCORESetSignMethod soap_tmp___ns1__SOF_USCORESetSignMethod;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCORESetSignMethod.ns1__SOF_USCORESetSignMethod = ns1__SOF_USCORESetSignMethod;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCORESetSignMethod(soap, &soap_tmp___ns1__SOF_USCORESetSignMethod);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCORESetSignMethod(soap, &soap_tmp___ns1__SOF_USCORESetSignMethod, "-ns1:SOF_SetSignMethod", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCORESetSignMethod(soap, &soap_tmp___ns1__SOF_USCORESetSignMethod, "-ns1:SOF_SetSignMethod", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCORESetSignMethodResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCORESetSignMethodResponse(soap, ns1__SOF_USCORESetSignMethodResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCORESetSignMethodResponse(soap, ns1__SOF_USCORESetSignMethodResponse, "ns1:SOF_SetSignMethodResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREGetTimeStampInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREGetTimeStampInfo *ns1__SOF_USCOREGetTimeStampInfo, struct ns1__SOF_USCOREGetTimeStampInfoResponse *ns1__SOF_USCOREGetTimeStampInfoResponse)
{	struct __ns1__SOF_USCOREGetTimeStampInfo soap_tmp___ns1__SOF_USCOREGetTimeStampInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREGetTimeStampInfo.ns1__SOF_USCOREGetTimeStampInfo = ns1__SOF_USCOREGetTimeStampInfo;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREGetTimeStampInfo(soap, &soap_tmp___ns1__SOF_USCOREGetTimeStampInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREGetTimeStampInfo(soap, &soap_tmp___ns1__SOF_USCOREGetTimeStampInfo, "-ns1:SOF_GetTimeStampInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREGetTimeStampInfo(soap, &soap_tmp___ns1__SOF_USCOREGetTimeStampInfo, "-ns1:SOF_GetTimeStampInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREGetTimeStampInfoResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREGetTimeStampInfoResponse(soap, ns1__SOF_USCOREGetTimeStampInfoResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREGetTimeStampInfoResponse(soap, ns1__SOF_USCOREGetTimeStampInfoResponse, "ns1:SOF_GetTimeStampInfoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREEncryptFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREEncryptFile *ns1__SOF_USCOREEncryptFile, struct ns1__SOF_USCOREEncryptFileResponse *ns1__SOF_USCOREEncryptFileResponse)
{	struct __ns1__SOF_USCOREEncryptFile soap_tmp___ns1__SOF_USCOREEncryptFile;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREEncryptFile.ns1__SOF_USCOREEncryptFile = ns1__SOF_USCOREEncryptFile;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREEncryptFile(soap, &soap_tmp___ns1__SOF_USCOREEncryptFile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREEncryptFile(soap, &soap_tmp___ns1__SOF_USCOREEncryptFile, "-ns1:SOF_EncryptFile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREEncryptFile(soap, &soap_tmp___ns1__SOF_USCOREEncryptFile, "-ns1:SOF_EncryptFile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREEncryptFileResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREEncryptFileResponse(soap, ns1__SOF_USCOREEncryptFileResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREEncryptFileResponse(soap, ns1__SOF_USCOREEncryptFileResponse, "ns1:SOF_EncryptFileResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCORESignDataByP7(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCORESignDataByP7 *ns1__SOF_USCORESignDataByP7, struct ns1__SOF_USCORESignDataByP7Response *ns1__SOF_USCORESignDataByP7Response)
{	struct __ns1__SOF_USCORESignDataByP7 soap_tmp___ns1__SOF_USCORESignDataByP7;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCORESignDataByP7.ns1__SOF_USCORESignDataByP7 = ns1__SOF_USCORESignDataByP7;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCORESignDataByP7(soap, &soap_tmp___ns1__SOF_USCORESignDataByP7);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCORESignDataByP7(soap, &soap_tmp___ns1__SOF_USCORESignDataByP7, "-ns1:SOF_SignDataByP7", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCORESignDataByP7(soap, &soap_tmp___ns1__SOF_USCORESignDataByP7, "-ns1:SOF_SignDataByP7", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCORESignDataByP7Response)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCORESignDataByP7Response(soap, ns1__SOF_USCORESignDataByP7Response);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCORESignDataByP7Response(soap, ns1__SOF_USCORESignDataByP7Response, "ns1:SOF_SignDataByP7Response", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREDecryptData(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREDecryptData *ns1__SOF_USCOREDecryptData, struct ns1__SOF_USCOREDecryptDataResponse *ns1__SOF_USCOREDecryptDataResponse)
{	struct __ns1__SOF_USCOREDecryptData soap_tmp___ns1__SOF_USCOREDecryptData;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREDecryptData.ns1__SOF_USCOREDecryptData = ns1__SOF_USCOREDecryptData;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREDecryptData(soap, &soap_tmp___ns1__SOF_USCOREDecryptData);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREDecryptData(soap, &soap_tmp___ns1__SOF_USCOREDecryptData, "-ns1:SOF_DecryptData", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREDecryptData(soap, &soap_tmp___ns1__SOF_USCOREDecryptData, "-ns1:SOF_DecryptData", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREDecryptDataResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREDecryptDataResponse(soap, ns1__SOF_USCOREDecryptDataResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREDecryptDataResponse(soap, ns1__SOF_USCOREDecryptDataResponse, "ns1:SOF_DecryptDataResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCORESignDataXML(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCORESignDataXML *ns1__SOF_USCORESignDataXML, struct ns1__SOF_USCORESignDataXMLResponse *ns1__SOF_USCORESignDataXMLResponse)
{	struct __ns1__SOF_USCORESignDataXML soap_tmp___ns1__SOF_USCORESignDataXML;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCORESignDataXML.ns1__SOF_USCORESignDataXML = ns1__SOF_USCORESignDataXML;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCORESignDataXML(soap, &soap_tmp___ns1__SOF_USCORESignDataXML);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCORESignDataXML(soap, &soap_tmp___ns1__SOF_USCORESignDataXML, "-ns1:SOF_SignDataXML", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCORESignDataXML(soap, &soap_tmp___ns1__SOF_USCORESignDataXML, "-ns1:SOF_SignDataXML", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCORESignDataXMLResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCORESignDataXMLResponse(soap, ns1__SOF_USCORESignDataXMLResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCORESignDataXMLResponse(soap, ns1__SOF_USCORESignDataXMLResponse, "ns1:SOF_SignDataXMLResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREGetCertInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREGetCertInfo *ns1__SOF_USCOREGetCertInfo, struct ns1__SOF_USCOREGetCertInfoResponse *ns1__SOF_USCOREGetCertInfoResponse)
{	struct __ns1__SOF_USCOREGetCertInfo soap_tmp___ns1__SOF_USCOREGetCertInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREGetCertInfo.ns1__SOF_USCOREGetCertInfo = ns1__SOF_USCOREGetCertInfo;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREGetCertInfo(soap, &soap_tmp___ns1__SOF_USCOREGetCertInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREGetCertInfo(soap, &soap_tmp___ns1__SOF_USCOREGetCertInfo, "-ns1:SOF_GetCertInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREGetCertInfo(soap, &soap_tmp___ns1__SOF_USCOREGetCertInfo, "-ns1:SOF_GetCertInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREGetCertInfoResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREGetCertInfoResponse(soap, ns1__SOF_USCOREGetCertInfoResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREGetCertInfoResponse(soap, ns1__SOF_USCOREGetCertInfoResponse, "ns1:SOF_GetCertInfoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREQueryCertTrustListAltNames(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREQueryCertTrustListAltNames *ns1__SOF_USCOREQueryCertTrustListAltNames, struct ns1__SOF_USCOREQueryCertTrustListAltNamesResponse *ns1__SOF_USCOREQueryCertTrustListAltNamesResponse)
{	struct __ns1__SOF_USCOREQueryCertTrustListAltNames soap_tmp___ns1__SOF_USCOREQueryCertTrustListAltNames;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREQueryCertTrustListAltNames.ns1__SOF_USCOREQueryCertTrustListAltNames = ns1__SOF_USCOREQueryCertTrustListAltNames;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREQueryCertTrustListAltNames(soap, &soap_tmp___ns1__SOF_USCOREQueryCertTrustListAltNames);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREQueryCertTrustListAltNames(soap, &soap_tmp___ns1__SOF_USCOREQueryCertTrustListAltNames, "-ns1:SOF_QueryCertTrustListAltNames", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREQueryCertTrustListAltNames(soap, &soap_tmp___ns1__SOF_USCOREQueryCertTrustListAltNames, "-ns1:SOF_QueryCertTrustListAltNames", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREQueryCertTrustListAltNamesResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREQueryCertTrustListAltNamesResponse(soap, ns1__SOF_USCOREQueryCertTrustListAltNamesResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREQueryCertTrustListAltNamesResponse(soap, ns1__SOF_USCOREQueryCertTrustListAltNamesResponse, "ns1:SOF_QueryCertTrustListAltNamesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SOF_USCOREEncryptData(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SOF_USCOREEncryptData *ns1__SOF_USCOREEncryptData, struct ns1__SOF_USCOREEncryptDataResponse *ns1__SOF_USCOREEncryptDataResponse)
{	struct __ns1__SOF_USCOREEncryptData soap_tmp___ns1__SOF_USCOREEncryptData;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/camanager/webservice/sOF_GenRandom";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__SOF_USCOREEncryptData.ns1__SOF_USCOREEncryptData = ns1__SOF_USCOREEncryptData;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SOF_USCOREEncryptData(soap, &soap_tmp___ns1__SOF_USCOREEncryptData);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SOF_USCOREEncryptData(soap, &soap_tmp___ns1__SOF_USCOREEncryptData, "-ns1:SOF_EncryptData", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SOF_USCOREEncryptData(soap, &soap_tmp___ns1__SOF_USCOREEncryptData, "-ns1:SOF_EncryptData", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SOF_USCOREEncryptDataResponse)
		return soap_closesock(soap);
	soap_default_ns1__SOF_USCOREEncryptDataResponse(soap, ns1__SOF_USCOREEncryptDataResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SOF_USCOREEncryptDataResponse(soap, ns1__SOF_USCOREEncryptDataResponse, "ns1:SOF_EncryptDataResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
