/* soapServer.cpp
   Generated by gSOAP 2.7.7 from SOF_interface.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.7.7 2017-06-07 11:08:02 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (!--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || soap_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_VerifySignedData"))
		return soap_serve___ns1__SOF_USCOREVerifySignedData(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_QueryCertTrustList"))
		return soap_serve___ns1__SOF_USCOREQueryCertTrustList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GetP7SignDataInfo"))
		return soap_serve___ns1__SOF_USCOREGetP7SignDataInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_SetCertTrustList"))
		return soap_serve___ns1__SOF_USCORESetCertTrustList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_VerifySignedDataByP7"))
		return soap_serve___ns1__SOF_USCOREVerifySignedDataByP7(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_PubKeyEncrypt"))
		return soap_serve___ns1__SOF_USCOREPubKeyEncrypt(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_VerifyTimeStamp"))
		return soap_serve___ns1__SOF_USCOREVerifyTimeStamp(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_VerifySignedFile"))
		return soap_serve___ns1__SOF_USCOREVerifySignedFile(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GetCertInfoByOid"))
		return soap_serve___ns1__SOF_USCOREGetCertInfoByOid(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GetServerCertificate"))
		return soap_serve___ns1__SOF_USCOREGetServerCertificate(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_DelCertTrustList"))
		return soap_serve___ns1__SOF_USCOREDelCertTrustList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GetXMLSignatureInfo"))
		return soap_serve___ns1__SOF_USCOREGetXMLSignatureInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_SignData"))
		return soap_serve___ns1__SOF_USCORESignData(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_VerifySignedDataXML"))
		return soap_serve___ns1__SOF_USCOREVerifySignedDataXML(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_SignFile"))
		return soap_serve___ns1__SOF_USCORESignFile(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GetInstance"))
		return soap_serve___ns1__SOF_USCOREGetInstance(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_PriKeyDecrypt"))
		return soap_serve___ns1__SOF_USCOREPriKeyDecrypt(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GenRandom"))
		return soap_serve___ns1__SOF_USCOREGenRandom(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GetSignMethod"))
		return soap_serve___ns1__SOF_USCOREGetSignMethod(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_SetWebAppName"))
		return soap_serve___ns1__SOF_USCORESetWebAppName(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_SetEncryptMethod"))
		return soap_serve___ns1__SOF_USCORESetEncryptMethod(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_CreateTimeStampRequest"))
		return soap_serve___ns1__SOF_USCORECreateTimeStampRequest(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GetEncryptMethod"))
		return soap_serve___ns1__SOF_USCOREGetEncryptMethod(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_CreateTimeStampResponse"))
		return soap_serve___ns1__SOF_USCORECreateTimeStampResponse(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_ValidateCert"))
		return soap_serve___ns1__SOF_USCOREValidateCert(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:DeleteFile"))
		return soap_serve___ns1__DeleteFile(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetFile"))
		return soap_serve___ns1__GetFile(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_DecryptFile"))
		return soap_serve___ns1__SOF_USCOREDecryptFile(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_SetSignMethod"))
		return soap_serve___ns1__SOF_USCORESetSignMethod(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GetTimeStampInfo"))
		return soap_serve___ns1__SOF_USCOREGetTimeStampInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_EncryptFile"))
		return soap_serve___ns1__SOF_USCOREEncryptFile(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_SignDataByP7"))
		return soap_serve___ns1__SOF_USCORESignDataByP7(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_DecryptData"))
		return soap_serve___ns1__SOF_USCOREDecryptData(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_SignDataXML"))
		return soap_serve___ns1__SOF_USCORESignDataXML(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_GetCertInfo"))
		return soap_serve___ns1__SOF_USCOREGetCertInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_QueryCertTrustListAltNames"))
		return soap_serve___ns1__SOF_USCOREQueryCertTrustListAltNames(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SOF_EncryptData"))
		return soap_serve___ns1__SOF_USCOREEncryptData(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREVerifySignedData(struct soap *soap)
{	struct __ns1__SOF_USCOREVerifySignedData soap_tmp___ns1__SOF_USCOREVerifySignedData;
	ns1__SOF_USCOREVerifySignedDataResponse ns1__SOF_USCOREVerifySignedDataResponse_;
	ns1__SOF_USCOREVerifySignedDataResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREVerifySignedData(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedData);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREVerifySignedData(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedData, "-ns1:SOF_VerifySignedData", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREVerifySignedData(soap, soap_tmp___ns1__SOF_USCOREVerifySignedData.ns1__SOF_USCOREVerifySignedData_, &ns1__SOF_USCOREVerifySignedDataResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREVerifySignedDataResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREVerifySignedDataResponse_.soap_put(soap, "ns1:SOF_VerifySignedDataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREVerifySignedDataResponse_.soap_put(soap, "ns1:SOF_VerifySignedDataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREQueryCertTrustList(struct soap *soap)
{	struct __ns1__SOF_USCOREQueryCertTrustList soap_tmp___ns1__SOF_USCOREQueryCertTrustList;
	ns1__SOF_USCOREQueryCertTrustListResponse ns1__SOF_USCOREQueryCertTrustListResponse_;
	ns1__SOF_USCOREQueryCertTrustListResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREQueryCertTrustList(soap, &soap_tmp___ns1__SOF_USCOREQueryCertTrustList);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREQueryCertTrustList(soap, &soap_tmp___ns1__SOF_USCOREQueryCertTrustList, "-ns1:SOF_QueryCertTrustList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREQueryCertTrustList(soap, soap_tmp___ns1__SOF_USCOREQueryCertTrustList.ns1__SOF_USCOREQueryCertTrustList_, &ns1__SOF_USCOREQueryCertTrustListResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREQueryCertTrustListResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREQueryCertTrustListResponse_.soap_put(soap, "ns1:SOF_QueryCertTrustListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREQueryCertTrustListResponse_.soap_put(soap, "ns1:SOF_QueryCertTrustListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGetP7SignDataInfo(struct soap *soap)
{	struct __ns1__SOF_USCOREGetP7SignDataInfo soap_tmp___ns1__SOF_USCOREGetP7SignDataInfo;
	ns1__SOF_USCOREGetP7SignDataInfoResponse ns1__SOF_USCOREGetP7SignDataInfoResponse_;
	ns1__SOF_USCOREGetP7SignDataInfoResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREGetP7SignDataInfo(soap, &soap_tmp___ns1__SOF_USCOREGetP7SignDataInfo);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREGetP7SignDataInfo(soap, &soap_tmp___ns1__SOF_USCOREGetP7SignDataInfo, "-ns1:SOF_GetP7SignDataInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGetP7SignDataInfo(soap, soap_tmp___ns1__SOF_USCOREGetP7SignDataInfo.ns1__SOF_USCOREGetP7SignDataInfo_, &ns1__SOF_USCOREGetP7SignDataInfoResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREGetP7SignDataInfoResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREGetP7SignDataInfoResponse_.soap_put(soap, "ns1:SOF_GetP7SignDataInfoResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREGetP7SignDataInfoResponse_.soap_put(soap, "ns1:SOF_GetP7SignDataInfoResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORESetCertTrustList(struct soap *soap)
{	struct __ns1__SOF_USCORESetCertTrustList soap_tmp___ns1__SOF_USCORESetCertTrustList;
	ns1__SOF_USCORESetCertTrustListResponse ns1__SOF_USCORESetCertTrustListResponse_;
	ns1__SOF_USCORESetCertTrustListResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCORESetCertTrustList(soap, &soap_tmp___ns1__SOF_USCORESetCertTrustList);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCORESetCertTrustList(soap, &soap_tmp___ns1__SOF_USCORESetCertTrustList, "-ns1:SOF_SetCertTrustList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORESetCertTrustList(soap, soap_tmp___ns1__SOF_USCORESetCertTrustList.ns1__SOF_USCORESetCertTrustList_, &ns1__SOF_USCORESetCertTrustListResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCORESetCertTrustListResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCORESetCertTrustListResponse_.soap_put(soap, "ns1:SOF_SetCertTrustListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCORESetCertTrustListResponse_.soap_put(soap, "ns1:SOF_SetCertTrustListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREVerifySignedDataByP7(struct soap *soap)
{	struct __ns1__SOF_USCOREVerifySignedDataByP7 soap_tmp___ns1__SOF_USCOREVerifySignedDataByP7;
	ns1__SOF_USCOREVerifySignedDataByP7Response ns1__SOF_USCOREVerifySignedDataByP7Response_;
	ns1__SOF_USCOREVerifySignedDataByP7Response_.soap_default(soap);
	soap_default___ns1__SOF_USCOREVerifySignedDataByP7(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedDataByP7);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREVerifySignedDataByP7(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedDataByP7, "-ns1:SOF_VerifySignedDataByP7", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREVerifySignedDataByP7(soap, soap_tmp___ns1__SOF_USCOREVerifySignedDataByP7.ns1__SOF_USCOREVerifySignedDataByP7_, &ns1__SOF_USCOREVerifySignedDataByP7Response_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREVerifySignedDataByP7Response_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREVerifySignedDataByP7Response_.soap_put(soap, "ns1:SOF_VerifySignedDataByP7Response", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREVerifySignedDataByP7Response_.soap_put(soap, "ns1:SOF_VerifySignedDataByP7Response", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREPubKeyEncrypt(struct soap *soap)
{	struct __ns1__SOF_USCOREPubKeyEncrypt soap_tmp___ns1__SOF_USCOREPubKeyEncrypt;
	ns1__SOF_USCOREPubKeyEncryptResponse ns1__SOF_USCOREPubKeyEncryptResponse_;
	ns1__SOF_USCOREPubKeyEncryptResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREPubKeyEncrypt(soap, &soap_tmp___ns1__SOF_USCOREPubKeyEncrypt);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREPubKeyEncrypt(soap, &soap_tmp___ns1__SOF_USCOREPubKeyEncrypt, "-ns1:SOF_PubKeyEncrypt", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREPubKeyEncrypt(soap, soap_tmp___ns1__SOF_USCOREPubKeyEncrypt.ns1__SOF_USCOREPubKeyEncrypt_, &ns1__SOF_USCOREPubKeyEncryptResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREPubKeyEncryptResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREPubKeyEncryptResponse_.soap_put(soap, "ns1:SOF_PubKeyEncryptResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREPubKeyEncryptResponse_.soap_put(soap, "ns1:SOF_PubKeyEncryptResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREVerifyTimeStamp(struct soap *soap)
{	struct __ns1__SOF_USCOREVerifyTimeStamp soap_tmp___ns1__SOF_USCOREVerifyTimeStamp;
	ns1__SOF_USCOREVerifyTimeStampResponse ns1__SOF_USCOREVerifyTimeStampResponse_;
	ns1__SOF_USCOREVerifyTimeStampResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREVerifyTimeStamp(soap, &soap_tmp___ns1__SOF_USCOREVerifyTimeStamp);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREVerifyTimeStamp(soap, &soap_tmp___ns1__SOF_USCOREVerifyTimeStamp, "-ns1:SOF_VerifyTimeStamp", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREVerifyTimeStamp(soap, soap_tmp___ns1__SOF_USCOREVerifyTimeStamp.ns1__SOF_USCOREVerifyTimeStamp_, &ns1__SOF_USCOREVerifyTimeStampResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREVerifyTimeStampResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREVerifyTimeStampResponse_.soap_put(soap, "ns1:SOF_VerifyTimeStampResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREVerifyTimeStampResponse_.soap_put(soap, "ns1:SOF_VerifyTimeStampResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREVerifySignedFile(struct soap *soap)
{	struct __ns1__SOF_USCOREVerifySignedFile soap_tmp___ns1__SOF_USCOREVerifySignedFile;
	ns1__SOF_USCOREVerifySignedFileResponse ns1__SOF_USCOREVerifySignedFileResponse_;
	ns1__SOF_USCOREVerifySignedFileResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREVerifySignedFile(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedFile);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREVerifySignedFile(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedFile, "-ns1:SOF_VerifySignedFile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREVerifySignedFile(soap, soap_tmp___ns1__SOF_USCOREVerifySignedFile.ns1__SOF_USCOREVerifySignedFile_, &ns1__SOF_USCOREVerifySignedFileResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREVerifySignedFileResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREVerifySignedFileResponse_.soap_put(soap, "ns1:SOF_VerifySignedFileResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREVerifySignedFileResponse_.soap_put(soap, "ns1:SOF_VerifySignedFileResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGetCertInfoByOid(struct soap *soap)
{	struct __ns1__SOF_USCOREGetCertInfoByOid soap_tmp___ns1__SOF_USCOREGetCertInfoByOid;
	ns1__SOF_USCOREGetCertInfoByOidResponse ns1__SOF_USCOREGetCertInfoByOidResponse_;
	ns1__SOF_USCOREGetCertInfoByOidResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREGetCertInfoByOid(soap, &soap_tmp___ns1__SOF_USCOREGetCertInfoByOid);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREGetCertInfoByOid(soap, &soap_tmp___ns1__SOF_USCOREGetCertInfoByOid, "-ns1:SOF_GetCertInfoByOid", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGetCertInfoByOid(soap, soap_tmp___ns1__SOF_USCOREGetCertInfoByOid.ns1__SOF_USCOREGetCertInfoByOid_, &ns1__SOF_USCOREGetCertInfoByOidResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREGetCertInfoByOidResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREGetCertInfoByOidResponse_.soap_put(soap, "ns1:SOF_GetCertInfoByOidResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREGetCertInfoByOidResponse_.soap_put(soap, "ns1:SOF_GetCertInfoByOidResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGetServerCertificate(struct soap *soap)
{	struct __ns1__SOF_USCOREGetServerCertificate soap_tmp___ns1__SOF_USCOREGetServerCertificate;
	ns1__SOF_USCOREGetServerCertificateResponse ns1__SOF_USCOREGetServerCertificateResponse_;
	ns1__SOF_USCOREGetServerCertificateResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREGetServerCertificate(soap, &soap_tmp___ns1__SOF_USCOREGetServerCertificate);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREGetServerCertificate(soap, &soap_tmp___ns1__SOF_USCOREGetServerCertificate, "-ns1:SOF_GetServerCertificate", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGetServerCertificate(soap, soap_tmp___ns1__SOF_USCOREGetServerCertificate.ns1__SOF_USCOREGetServerCertificate_, &ns1__SOF_USCOREGetServerCertificateResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREGetServerCertificateResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREGetServerCertificateResponse_.soap_put(soap, "ns1:SOF_GetServerCertificateResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREGetServerCertificateResponse_.soap_put(soap, "ns1:SOF_GetServerCertificateResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREDelCertTrustList(struct soap *soap)
{	struct __ns1__SOF_USCOREDelCertTrustList soap_tmp___ns1__SOF_USCOREDelCertTrustList;
	ns1__SOF_USCOREDelCertTrustListResponse ns1__SOF_USCOREDelCertTrustListResponse_;
	ns1__SOF_USCOREDelCertTrustListResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREDelCertTrustList(soap, &soap_tmp___ns1__SOF_USCOREDelCertTrustList);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREDelCertTrustList(soap, &soap_tmp___ns1__SOF_USCOREDelCertTrustList, "-ns1:SOF_DelCertTrustList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREDelCertTrustList(soap, soap_tmp___ns1__SOF_USCOREDelCertTrustList.ns1__SOF_USCOREDelCertTrustList_, &ns1__SOF_USCOREDelCertTrustListResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREDelCertTrustListResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREDelCertTrustListResponse_.soap_put(soap, "ns1:SOF_DelCertTrustListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREDelCertTrustListResponse_.soap_put(soap, "ns1:SOF_DelCertTrustListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGetXMLSignatureInfo(struct soap *soap)
{	struct __ns1__SOF_USCOREGetXMLSignatureInfo soap_tmp___ns1__SOF_USCOREGetXMLSignatureInfo;
	ns1__SOF_USCOREGetXMLSignatureInfoResponse ns1__SOF_USCOREGetXMLSignatureInfoResponse_;
	ns1__SOF_USCOREGetXMLSignatureInfoResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREGetXMLSignatureInfo(soap, &soap_tmp___ns1__SOF_USCOREGetXMLSignatureInfo);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREGetXMLSignatureInfo(soap, &soap_tmp___ns1__SOF_USCOREGetXMLSignatureInfo, "-ns1:SOF_GetXMLSignatureInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGetXMLSignatureInfo(soap, soap_tmp___ns1__SOF_USCOREGetXMLSignatureInfo.ns1__SOF_USCOREGetXMLSignatureInfo_, &ns1__SOF_USCOREGetXMLSignatureInfoResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREGetXMLSignatureInfoResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREGetXMLSignatureInfoResponse_.soap_put(soap, "ns1:SOF_GetXMLSignatureInfoResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREGetXMLSignatureInfoResponse_.soap_put(soap, "ns1:SOF_GetXMLSignatureInfoResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORESignData(struct soap *soap)
{	struct __ns1__SOF_USCORESignData soap_tmp___ns1__SOF_USCORESignData;
	ns1__SOF_USCORESignDataResponse ns1__SOF_USCORESignDataResponse_;
	ns1__SOF_USCORESignDataResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCORESignData(soap, &soap_tmp___ns1__SOF_USCORESignData);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCORESignData(soap, &soap_tmp___ns1__SOF_USCORESignData, "-ns1:SOF_SignData", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORESignData(soap, soap_tmp___ns1__SOF_USCORESignData.ns1__SOF_USCORESignData_, &ns1__SOF_USCORESignDataResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCORESignDataResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCORESignDataResponse_.soap_put(soap, "ns1:SOF_SignDataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCORESignDataResponse_.soap_put(soap, "ns1:SOF_SignDataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREVerifySignedDataXML(struct soap *soap)
{	struct __ns1__SOF_USCOREVerifySignedDataXML soap_tmp___ns1__SOF_USCOREVerifySignedDataXML;
	ns1__SOF_USCOREVerifySignedDataXMLResponse ns1__SOF_USCOREVerifySignedDataXMLResponse_;
	ns1__SOF_USCOREVerifySignedDataXMLResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREVerifySignedDataXML(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedDataXML);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREVerifySignedDataXML(soap, &soap_tmp___ns1__SOF_USCOREVerifySignedDataXML, "-ns1:SOF_VerifySignedDataXML", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREVerifySignedDataXML(soap, soap_tmp___ns1__SOF_USCOREVerifySignedDataXML.ns1__SOF_USCOREVerifySignedDataXML_, &ns1__SOF_USCOREVerifySignedDataXMLResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREVerifySignedDataXMLResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREVerifySignedDataXMLResponse_.soap_put(soap, "ns1:SOF_VerifySignedDataXMLResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREVerifySignedDataXMLResponse_.soap_put(soap, "ns1:SOF_VerifySignedDataXMLResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORESignFile(struct soap *soap)
{	struct __ns1__SOF_USCORESignFile soap_tmp___ns1__SOF_USCORESignFile;
	ns1__SOF_USCORESignFileResponse ns1__SOF_USCORESignFileResponse_;
	ns1__SOF_USCORESignFileResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCORESignFile(soap, &soap_tmp___ns1__SOF_USCORESignFile);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCORESignFile(soap, &soap_tmp___ns1__SOF_USCORESignFile, "-ns1:SOF_SignFile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORESignFile(soap, soap_tmp___ns1__SOF_USCORESignFile.ns1__SOF_USCORESignFile_, &ns1__SOF_USCORESignFileResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCORESignFileResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCORESignFileResponse_.soap_put(soap, "ns1:SOF_SignFileResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCORESignFileResponse_.soap_put(soap, "ns1:SOF_SignFileResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGetInstance(struct soap *soap)
{	struct __ns1__SOF_USCOREGetInstance soap_tmp___ns1__SOF_USCOREGetInstance;
	ns1__SOF_USCOREGetInstanceResponse ns1__SOF_USCOREGetInstanceResponse_;
	ns1__SOF_USCOREGetInstanceResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREGetInstance(soap, &soap_tmp___ns1__SOF_USCOREGetInstance);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREGetInstance(soap, &soap_tmp___ns1__SOF_USCOREGetInstance, "-ns1:SOF_GetInstance", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGetInstance(soap, soap_tmp___ns1__SOF_USCOREGetInstance.ns1__SOF_USCOREGetInstance_, &ns1__SOF_USCOREGetInstanceResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREGetInstanceResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREGetInstanceResponse_.soap_put(soap, "ns1:SOF_GetInstanceResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREGetInstanceResponse_.soap_put(soap, "ns1:SOF_GetInstanceResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREPriKeyDecrypt(struct soap *soap)
{	struct __ns1__SOF_USCOREPriKeyDecrypt soap_tmp___ns1__SOF_USCOREPriKeyDecrypt;
	ns1__SOF_USCOREPriKeyDecryptResponse ns1__SOF_USCOREPriKeyDecryptResponse_;
	ns1__SOF_USCOREPriKeyDecryptResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREPriKeyDecrypt(soap, &soap_tmp___ns1__SOF_USCOREPriKeyDecrypt);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREPriKeyDecrypt(soap, &soap_tmp___ns1__SOF_USCOREPriKeyDecrypt, "-ns1:SOF_PriKeyDecrypt", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREPriKeyDecrypt(soap, soap_tmp___ns1__SOF_USCOREPriKeyDecrypt.ns1__SOF_USCOREPriKeyDecrypt_, &ns1__SOF_USCOREPriKeyDecryptResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREPriKeyDecryptResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREPriKeyDecryptResponse_.soap_put(soap, "ns1:SOF_PriKeyDecryptResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREPriKeyDecryptResponse_.soap_put(soap, "ns1:SOF_PriKeyDecryptResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGenRandom(struct soap *soap)
{	struct __ns1__SOF_USCOREGenRandom soap_tmp___ns1__SOF_USCOREGenRandom;
	ns1__SOF_USCOREGenRandomResponse ns1__SOF_USCOREGenRandomResponse_;
	ns1__SOF_USCOREGenRandomResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREGenRandom(soap, &soap_tmp___ns1__SOF_USCOREGenRandom);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREGenRandom(soap, &soap_tmp___ns1__SOF_USCOREGenRandom, "-ns1:SOF_GenRandom", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGenRandom(soap, soap_tmp___ns1__SOF_USCOREGenRandom.ns1__SOF_USCOREGenRandom_, &ns1__SOF_USCOREGenRandomResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREGenRandomResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREGenRandomResponse_.soap_put(soap, "ns1:SOF_GenRandomResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREGenRandomResponse_.soap_put(soap, "ns1:SOF_GenRandomResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGetSignMethod(struct soap *soap)
{	struct __ns1__SOF_USCOREGetSignMethod soap_tmp___ns1__SOF_USCOREGetSignMethod;
	ns1__SOF_USCOREGetSignMethodResponse ns1__SOF_USCOREGetSignMethodResponse_;
	ns1__SOF_USCOREGetSignMethodResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREGetSignMethod(soap, &soap_tmp___ns1__SOF_USCOREGetSignMethod);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREGetSignMethod(soap, &soap_tmp___ns1__SOF_USCOREGetSignMethod, "-ns1:SOF_GetSignMethod", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGetSignMethod(soap, soap_tmp___ns1__SOF_USCOREGetSignMethod.ns1__SOF_USCOREGetSignMethod_, &ns1__SOF_USCOREGetSignMethodResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREGetSignMethodResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREGetSignMethodResponse_.soap_put(soap, "ns1:SOF_GetSignMethodResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREGetSignMethodResponse_.soap_put(soap, "ns1:SOF_GetSignMethodResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORESetWebAppName(struct soap *soap)
{	struct __ns1__SOF_USCORESetWebAppName soap_tmp___ns1__SOF_USCORESetWebAppName;
	ns1__SOF_USCORESetWebAppNameResponse ns1__SOF_USCORESetWebAppNameResponse_;
	ns1__SOF_USCORESetWebAppNameResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCORESetWebAppName(soap, &soap_tmp___ns1__SOF_USCORESetWebAppName);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCORESetWebAppName(soap, &soap_tmp___ns1__SOF_USCORESetWebAppName, "-ns1:SOF_SetWebAppName", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORESetWebAppName(soap, soap_tmp___ns1__SOF_USCORESetWebAppName.ns1__SOF_USCORESetWebAppName_, &ns1__SOF_USCORESetWebAppNameResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCORESetWebAppNameResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCORESetWebAppNameResponse_.soap_put(soap, "ns1:SOF_SetWebAppNameResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCORESetWebAppNameResponse_.soap_put(soap, "ns1:SOF_SetWebAppNameResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORESetEncryptMethod(struct soap *soap)
{	struct __ns1__SOF_USCORESetEncryptMethod soap_tmp___ns1__SOF_USCORESetEncryptMethod;
	ns1__SOF_USCORESetEncryptMethodResponse ns1__SOF_USCORESetEncryptMethodResponse_;
	ns1__SOF_USCORESetEncryptMethodResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCORESetEncryptMethod(soap, &soap_tmp___ns1__SOF_USCORESetEncryptMethod);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCORESetEncryptMethod(soap, &soap_tmp___ns1__SOF_USCORESetEncryptMethod, "-ns1:SOF_SetEncryptMethod", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORESetEncryptMethod(soap, soap_tmp___ns1__SOF_USCORESetEncryptMethod.ns1__SOF_USCORESetEncryptMethod_, &ns1__SOF_USCORESetEncryptMethodResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCORESetEncryptMethodResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCORESetEncryptMethodResponse_.soap_put(soap, "ns1:SOF_SetEncryptMethodResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCORESetEncryptMethodResponse_.soap_put(soap, "ns1:SOF_SetEncryptMethodResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORECreateTimeStampRequest(struct soap *soap)
{	struct __ns1__SOF_USCORECreateTimeStampRequest soap_tmp___ns1__SOF_USCORECreateTimeStampRequest;
	ns1__SOF_USCORECreateTimeStampRequestResponse ns1__SOF_USCORECreateTimeStampRequestResponse_;
	ns1__SOF_USCORECreateTimeStampRequestResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCORECreateTimeStampRequest(soap, &soap_tmp___ns1__SOF_USCORECreateTimeStampRequest);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCORECreateTimeStampRequest(soap, &soap_tmp___ns1__SOF_USCORECreateTimeStampRequest, "-ns1:SOF_CreateTimeStampRequest", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORECreateTimeStampRequest(soap, soap_tmp___ns1__SOF_USCORECreateTimeStampRequest.ns1__SOF_USCORECreateTimeStampRequest_, &ns1__SOF_USCORECreateTimeStampRequestResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCORECreateTimeStampRequestResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCORECreateTimeStampRequestResponse_.soap_put(soap, "ns1:SOF_CreateTimeStampRequestResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCORECreateTimeStampRequestResponse_.soap_put(soap, "ns1:SOF_CreateTimeStampRequestResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGetEncryptMethod(struct soap *soap)
{	struct __ns1__SOF_USCOREGetEncryptMethod soap_tmp___ns1__SOF_USCOREGetEncryptMethod;
	ns1__SOF_USCOREGetEncryptMethodResponse ns1__SOF_USCOREGetEncryptMethodResponse_;
	ns1__SOF_USCOREGetEncryptMethodResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREGetEncryptMethod(soap, &soap_tmp___ns1__SOF_USCOREGetEncryptMethod);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREGetEncryptMethod(soap, &soap_tmp___ns1__SOF_USCOREGetEncryptMethod, "-ns1:SOF_GetEncryptMethod", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGetEncryptMethod(soap, soap_tmp___ns1__SOF_USCOREGetEncryptMethod.ns1__SOF_USCOREGetEncryptMethod_, &ns1__SOF_USCOREGetEncryptMethodResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREGetEncryptMethodResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREGetEncryptMethodResponse_.soap_put(soap, "ns1:SOF_GetEncryptMethodResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREGetEncryptMethodResponse_.soap_put(soap, "ns1:SOF_GetEncryptMethodResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORECreateTimeStampResponse(struct soap *soap)
{	struct __ns1__SOF_USCORECreateTimeStampResponse soap_tmp___ns1__SOF_USCORECreateTimeStampResponse;
	ns1__SOF_USCORECreateTimeStampResponseResponse ns1__SOF_USCORECreateTimeStampResponseResponse_;
	ns1__SOF_USCORECreateTimeStampResponseResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCORECreateTimeStampResponse(soap, &soap_tmp___ns1__SOF_USCORECreateTimeStampResponse);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCORECreateTimeStampResponse(soap, &soap_tmp___ns1__SOF_USCORECreateTimeStampResponse, "-ns1:SOF_CreateTimeStampResponse", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORECreateTimeStampResponse(soap, soap_tmp___ns1__SOF_USCORECreateTimeStampResponse.ns1__SOF_USCORECreateTimeStampResponse_, &ns1__SOF_USCORECreateTimeStampResponseResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCORECreateTimeStampResponseResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCORECreateTimeStampResponseResponse_.soap_put(soap, "ns1:SOF_CreateTimeStampResponseResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCORECreateTimeStampResponseResponse_.soap_put(soap, "ns1:SOF_CreateTimeStampResponseResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREValidateCert(struct soap *soap)
{	struct __ns1__SOF_USCOREValidateCert soap_tmp___ns1__SOF_USCOREValidateCert;
	ns1__SOF_USCOREValidateCertResponse ns1__SOF_USCOREValidateCertResponse_;
	ns1__SOF_USCOREValidateCertResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREValidateCert(soap, &soap_tmp___ns1__SOF_USCOREValidateCert);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREValidateCert(soap, &soap_tmp___ns1__SOF_USCOREValidateCert, "-ns1:SOF_ValidateCert", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREValidateCert(soap, soap_tmp___ns1__SOF_USCOREValidateCert.ns1__SOF_USCOREValidateCert_, &ns1__SOF_USCOREValidateCertResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREValidateCertResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREValidateCertResponse_.soap_put(soap, "ns1:SOF_ValidateCertResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREValidateCertResponse_.soap_put(soap, "ns1:SOF_ValidateCertResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__DeleteFile(struct soap *soap)
{	struct __ns1__DeleteFile soap_tmp___ns1__DeleteFile;
	ns1__DeleteFileResponse ns1__DeleteFileResponse_;
	ns1__DeleteFileResponse_.soap_default(soap);
	soap_default___ns1__DeleteFile(soap, &soap_tmp___ns1__DeleteFile);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__DeleteFile(soap, &soap_tmp___ns1__DeleteFile, "-ns1:DeleteFile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__DeleteFile(soap, soap_tmp___ns1__DeleteFile.ns1__DeleteFile_, &ns1__DeleteFileResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__DeleteFileResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__DeleteFileResponse_.soap_put(soap, "ns1:DeleteFileResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__DeleteFileResponse_.soap_put(soap, "ns1:DeleteFileResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetFile(struct soap *soap)
{	struct __ns1__GetFile soap_tmp___ns1__GetFile;
	ns1__GetFileResponse ns1__GetFileResponse_;
	ns1__GetFileResponse_.soap_default(soap);
	soap_default___ns1__GetFile(soap, &soap_tmp___ns1__GetFile);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GetFile(soap, &soap_tmp___ns1__GetFile, "-ns1:GetFile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetFile(soap, soap_tmp___ns1__GetFile.ns1__GetFile_, &ns1__GetFileResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__GetFileResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetFileResponse_.soap_put(soap, "ns1:GetFileResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetFileResponse_.soap_put(soap, "ns1:GetFileResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREDecryptFile(struct soap *soap)
{	struct __ns1__SOF_USCOREDecryptFile soap_tmp___ns1__SOF_USCOREDecryptFile;
	ns1__SOF_USCOREDecryptFileResponse ns1__SOF_USCOREDecryptFileResponse_;
	ns1__SOF_USCOREDecryptFileResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREDecryptFile(soap, &soap_tmp___ns1__SOF_USCOREDecryptFile);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREDecryptFile(soap, &soap_tmp___ns1__SOF_USCOREDecryptFile, "-ns1:SOF_DecryptFile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREDecryptFile(soap, soap_tmp___ns1__SOF_USCOREDecryptFile.ns1__SOF_USCOREDecryptFile_, &ns1__SOF_USCOREDecryptFileResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREDecryptFileResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREDecryptFileResponse_.soap_put(soap, "ns1:SOF_DecryptFileResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREDecryptFileResponse_.soap_put(soap, "ns1:SOF_DecryptFileResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORESetSignMethod(struct soap *soap)
{	struct __ns1__SOF_USCORESetSignMethod soap_tmp___ns1__SOF_USCORESetSignMethod;
	ns1__SOF_USCORESetSignMethodResponse ns1__SOF_USCORESetSignMethodResponse_;
	ns1__SOF_USCORESetSignMethodResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCORESetSignMethod(soap, &soap_tmp___ns1__SOF_USCORESetSignMethod);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCORESetSignMethod(soap, &soap_tmp___ns1__SOF_USCORESetSignMethod, "-ns1:SOF_SetSignMethod", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORESetSignMethod(soap, soap_tmp___ns1__SOF_USCORESetSignMethod.ns1__SOF_USCORESetSignMethod_, &ns1__SOF_USCORESetSignMethodResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCORESetSignMethodResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCORESetSignMethodResponse_.soap_put(soap, "ns1:SOF_SetSignMethodResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCORESetSignMethodResponse_.soap_put(soap, "ns1:SOF_SetSignMethodResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGetTimeStampInfo(struct soap *soap)
{	struct __ns1__SOF_USCOREGetTimeStampInfo soap_tmp___ns1__SOF_USCOREGetTimeStampInfo;
	ns1__SOF_USCOREGetTimeStampInfoResponse ns1__SOF_USCOREGetTimeStampInfoResponse_;
	ns1__SOF_USCOREGetTimeStampInfoResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREGetTimeStampInfo(soap, &soap_tmp___ns1__SOF_USCOREGetTimeStampInfo);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREGetTimeStampInfo(soap, &soap_tmp___ns1__SOF_USCOREGetTimeStampInfo, "-ns1:SOF_GetTimeStampInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGetTimeStampInfo(soap, soap_tmp___ns1__SOF_USCOREGetTimeStampInfo.ns1__SOF_USCOREGetTimeStampInfo_, &ns1__SOF_USCOREGetTimeStampInfoResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREGetTimeStampInfoResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREGetTimeStampInfoResponse_.soap_put(soap, "ns1:SOF_GetTimeStampInfoResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREGetTimeStampInfoResponse_.soap_put(soap, "ns1:SOF_GetTimeStampInfoResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREEncryptFile(struct soap *soap)
{	struct __ns1__SOF_USCOREEncryptFile soap_tmp___ns1__SOF_USCOREEncryptFile;
	ns1__SOF_USCOREEncryptFileResponse ns1__SOF_USCOREEncryptFileResponse_;
	ns1__SOF_USCOREEncryptFileResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREEncryptFile(soap, &soap_tmp___ns1__SOF_USCOREEncryptFile);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREEncryptFile(soap, &soap_tmp___ns1__SOF_USCOREEncryptFile, "-ns1:SOF_EncryptFile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREEncryptFile(soap, soap_tmp___ns1__SOF_USCOREEncryptFile.ns1__SOF_USCOREEncryptFile_, &ns1__SOF_USCOREEncryptFileResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREEncryptFileResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREEncryptFileResponse_.soap_put(soap, "ns1:SOF_EncryptFileResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREEncryptFileResponse_.soap_put(soap, "ns1:SOF_EncryptFileResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORESignDataByP7(struct soap *soap)
{	struct __ns1__SOF_USCORESignDataByP7 soap_tmp___ns1__SOF_USCORESignDataByP7;
	ns1__SOF_USCORESignDataByP7Response ns1__SOF_USCORESignDataByP7Response_;
	ns1__SOF_USCORESignDataByP7Response_.soap_default(soap);
	soap_default___ns1__SOF_USCORESignDataByP7(soap, &soap_tmp___ns1__SOF_USCORESignDataByP7);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCORESignDataByP7(soap, &soap_tmp___ns1__SOF_USCORESignDataByP7, "-ns1:SOF_SignDataByP7", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORESignDataByP7(soap, soap_tmp___ns1__SOF_USCORESignDataByP7.ns1__SOF_USCORESignDataByP7_, &ns1__SOF_USCORESignDataByP7Response_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCORESignDataByP7Response_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCORESignDataByP7Response_.soap_put(soap, "ns1:SOF_SignDataByP7Response", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCORESignDataByP7Response_.soap_put(soap, "ns1:SOF_SignDataByP7Response", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREDecryptData(struct soap *soap)
{	struct __ns1__SOF_USCOREDecryptData soap_tmp___ns1__SOF_USCOREDecryptData;
	ns1__SOF_USCOREDecryptDataResponse ns1__SOF_USCOREDecryptDataResponse_;
	ns1__SOF_USCOREDecryptDataResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREDecryptData(soap, &soap_tmp___ns1__SOF_USCOREDecryptData);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREDecryptData(soap, &soap_tmp___ns1__SOF_USCOREDecryptData, "-ns1:SOF_DecryptData", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREDecryptData(soap, soap_tmp___ns1__SOF_USCOREDecryptData.ns1__SOF_USCOREDecryptData_, &ns1__SOF_USCOREDecryptDataResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREDecryptDataResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREDecryptDataResponse_.soap_put(soap, "ns1:SOF_DecryptDataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREDecryptDataResponse_.soap_put(soap, "ns1:SOF_DecryptDataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCORESignDataXML(struct soap *soap)
{	struct __ns1__SOF_USCORESignDataXML soap_tmp___ns1__SOF_USCORESignDataXML;
	ns1__SOF_USCORESignDataXMLResponse ns1__SOF_USCORESignDataXMLResponse_;
	ns1__SOF_USCORESignDataXMLResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCORESignDataXML(soap, &soap_tmp___ns1__SOF_USCORESignDataXML);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCORESignDataXML(soap, &soap_tmp___ns1__SOF_USCORESignDataXML, "-ns1:SOF_SignDataXML", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCORESignDataXML(soap, soap_tmp___ns1__SOF_USCORESignDataXML.ns1__SOF_USCORESignDataXML_, &ns1__SOF_USCORESignDataXMLResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCORESignDataXMLResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCORESignDataXMLResponse_.soap_put(soap, "ns1:SOF_SignDataXMLResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCORESignDataXMLResponse_.soap_put(soap, "ns1:SOF_SignDataXMLResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREGetCertInfo(struct soap *soap)
{	struct __ns1__SOF_USCOREGetCertInfo soap_tmp___ns1__SOF_USCOREGetCertInfo;
	ns1__SOF_USCOREGetCertInfoResponse ns1__SOF_USCOREGetCertInfoResponse_;
	ns1__SOF_USCOREGetCertInfoResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREGetCertInfo(soap, &soap_tmp___ns1__SOF_USCOREGetCertInfo);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREGetCertInfo(soap, &soap_tmp___ns1__SOF_USCOREGetCertInfo, "-ns1:SOF_GetCertInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREGetCertInfo(soap, soap_tmp___ns1__SOF_USCOREGetCertInfo.ns1__SOF_USCOREGetCertInfo_, &ns1__SOF_USCOREGetCertInfoResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREGetCertInfoResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREGetCertInfoResponse_.soap_put(soap, "ns1:SOF_GetCertInfoResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREGetCertInfoResponse_.soap_put(soap, "ns1:SOF_GetCertInfoResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREQueryCertTrustListAltNames(struct soap *soap)
{	struct __ns1__SOF_USCOREQueryCertTrustListAltNames soap_tmp___ns1__SOF_USCOREQueryCertTrustListAltNames;
	ns1__SOF_USCOREQueryCertTrustListAltNamesResponse ns1__SOF_USCOREQueryCertTrustListAltNamesResponse_;
	ns1__SOF_USCOREQueryCertTrustListAltNamesResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREQueryCertTrustListAltNames(soap, &soap_tmp___ns1__SOF_USCOREQueryCertTrustListAltNames);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREQueryCertTrustListAltNames(soap, &soap_tmp___ns1__SOF_USCOREQueryCertTrustListAltNames, "-ns1:SOF_QueryCertTrustListAltNames", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREQueryCertTrustListAltNames(soap, soap_tmp___ns1__SOF_USCOREQueryCertTrustListAltNames.ns1__SOF_USCOREQueryCertTrustListAltNames_, &ns1__SOF_USCOREQueryCertTrustListAltNamesResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREQueryCertTrustListAltNamesResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREQueryCertTrustListAltNamesResponse_.soap_put(soap, "ns1:SOF_QueryCertTrustListAltNamesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREQueryCertTrustListAltNamesResponse_.soap_put(soap, "ns1:SOF_QueryCertTrustListAltNamesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SOF_USCOREEncryptData(struct soap *soap)
{	struct __ns1__SOF_USCOREEncryptData soap_tmp___ns1__SOF_USCOREEncryptData;
	ns1__SOF_USCOREEncryptDataResponse ns1__SOF_USCOREEncryptDataResponse_;
	ns1__SOF_USCOREEncryptDataResponse_.soap_default(soap);
	soap_default___ns1__SOF_USCOREEncryptData(soap, &soap_tmp___ns1__SOF_USCOREEncryptData);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SOF_USCOREEncryptData(soap, &soap_tmp___ns1__SOF_USCOREEncryptData, "-ns1:SOF_EncryptData", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SOF_USCOREEncryptData(soap, soap_tmp___ns1__SOF_USCOREEncryptData.ns1__SOF_USCOREEncryptData_, &ns1__SOF_USCOREEncryptDataResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SOF_USCOREEncryptDataResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SOF_USCOREEncryptDataResponse_.soap_put(soap, "ns1:SOF_EncryptDataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SOF_USCOREEncryptDataResponse_.soap_put(soap, "ns1:SOF_EncryptDataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

/* End of soapServer.cpp */
