/* soapStub.h
   Generated by gSOAP 2.7.7 from SOF_interface.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include <vector>
#include "stdsoap2.h"

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/




#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (7)
/* Base64 schema type: */
class SOAP_CMAC xsd__base64Binary
{
public:
	unsigned char *__ptr;
	int __size;
	char *id;	/* optional element of type xsd:string */
	char *type;	/* optional element of type xsd:string */
	char *options;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 7; } /* = unique id SOAP_TYPE_xsd__base64Binary */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         xsd__base64Binary() : __ptr(NULL), id(NULL), type(NULL), options(NULL), soap(NULL) { }
	virtual ~xsd__base64Binary() { }
};
#endif

#if 0 /* volatile type: do no redeclare */

#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREVerifySignedData
#define SOAP_TYPE_WS1__SOF_USCOREVerifySignedData (13)
/* WS1:SOF_VerifySignedData */
class SOAP_CMAC WS1__SOF_USCOREVerifySignedData
{
public:
	std::wstring *base64EncodeCert;	/* optional element of type xsd:string */
	std::wstring *inData;	/* optional element of type xsd:string */
	std::wstring *signValue;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 13; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREVerifySignedData */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREVerifySignedData() : base64EncodeCert(NULL), inData(NULL), signValue(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREVerifySignedData() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREVerifySignedDataResponse
#define SOAP_TYPE_WS1__SOF_USCOREVerifySignedDataResponse (14)
/* WS1:SOF_VerifySignedDataResponse */
class SOAP_CMAC WS1__SOF_USCOREVerifySignedDataResponse
{
public:
	bool return_;	/* RPC return element */	/* required element of type xsd:boolean */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 14; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREVerifySignedDataResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREVerifySignedDataResponse() : soap(NULL) { }
	virtual ~WS1__SOF_USCOREVerifySignedDataResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREQueryCertTrustList
#define SOAP_TYPE_WS1__SOF_USCOREQueryCertTrustList (15)
/* WS1:SOF_QueryCertTrustList */
class SOAP_CMAC WS1__SOF_USCOREQueryCertTrustList
{
public:
	std::wstring *fCtlAltname;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 15; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREQueryCertTrustList */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREQueryCertTrustList() : fCtlAltname(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREQueryCertTrustList() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREQueryCertTrustListResponse
#define SOAP_TYPE_WS1__SOF_USCOREQueryCertTrustListResponse (16)
/* WS1:SOF_QueryCertTrustListResponse */
class SOAP_CMAC WS1__SOF_USCOREQueryCertTrustListResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 16; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREQueryCertTrustListResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREQueryCertTrustListResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREQueryCertTrustListResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREVerifySignedDataByP7
#define SOAP_TYPE_WS1__SOF_USCOREVerifySignedDataByP7 (17)
/* WS1:SOF_VerifySignedDataByP7 */
class SOAP_CMAC WS1__SOF_USCOREVerifySignedDataByP7
{
public:
	std::wstring *pkcs7SignData;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 17; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREVerifySignedDataByP7 */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREVerifySignedDataByP7() : pkcs7SignData(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREVerifySignedDataByP7() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREVerifySignedDataByP7Response
#define SOAP_TYPE_WS1__SOF_USCOREVerifySignedDataByP7Response (18)
/* WS1:SOF_VerifySignedDataByP7Response */
class SOAP_CMAC WS1__SOF_USCOREVerifySignedDataByP7Response
{
public:
	bool return_;	/* RPC return element */	/* required element of type xsd:boolean */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 18; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREVerifySignedDataByP7Response */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREVerifySignedDataByP7Response() : soap(NULL) { }
	virtual ~WS1__SOF_USCOREVerifySignedDataByP7Response() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORESetCertTrustList
#define SOAP_TYPE_WS1__SOF_USCORESetCertTrustList (19)
/* WS1:SOF_SetCertTrustList */
class SOAP_CMAC WS1__SOF_USCORESetCertTrustList
{
public:
	std::wstring *fCtlAltname;	/* optional element of type xsd:string */
	std::wstring *fCtlContent;	/* optional element of type xsd:string */
	int fCtlContentLen;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 19; } /* = unique id SOAP_TYPE_WS1__SOF_USCORESetCertTrustList */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORESetCertTrustList() : fCtlAltname(NULL), fCtlContent(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCORESetCertTrustList() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORESetCertTrustListResponse
#define SOAP_TYPE_WS1__SOF_USCORESetCertTrustListResponse (20)
/* WS1:SOF_SetCertTrustListResponse */
class SOAP_CMAC WS1__SOF_USCORESetCertTrustListResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 20; } /* = unique id SOAP_TYPE_WS1__SOF_USCORESetCertTrustListResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORESetCertTrustListResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCORESetCertTrustListResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGetP7SignDataInfo
#define SOAP_TYPE_WS1__SOF_USCOREGetP7SignDataInfo (21)
/* WS1:SOF_GetP7SignDataInfo */
class SOAP_CMAC WS1__SOF_USCOREGetP7SignDataInfo
{
public:
	std::wstring *pkcs7SignData;	/* optional element of type xsd:string */
	int type;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 21; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGetP7SignDataInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGetP7SignDataInfo() : pkcs7SignData(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREGetP7SignDataInfo() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGetP7SignDataInfoResponse
#define SOAP_TYPE_WS1__SOF_USCOREGetP7SignDataInfoResponse (22)
/* WS1:SOF_GetP7SignDataInfoResponse */
class SOAP_CMAC WS1__SOF_USCOREGetP7SignDataInfoResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 22; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGetP7SignDataInfoResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGetP7SignDataInfoResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREGetP7SignDataInfoResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREVerifyTimeStamp
#define SOAP_TYPE_WS1__SOF_USCOREVerifyTimeStamp (23)
/* WS1:SOF_VerifyTimeStamp */
class SOAP_CMAC WS1__SOF_USCOREVerifyTimeStamp
{
public:
	std::wstring *content;	/* optional element of type xsd:string */
	std::wstring *tsResponseData;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 23; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREVerifyTimeStamp */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREVerifyTimeStamp() : content(NULL), tsResponseData(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREVerifyTimeStamp() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREVerifyTimeStampResponse
#define SOAP_TYPE_WS1__SOF_USCOREVerifyTimeStampResponse (24)
/* WS1:SOF_VerifyTimeStampResponse */
class SOAP_CMAC WS1__SOF_USCOREVerifyTimeStampResponse
{
public:
	bool return_;	/* RPC return element */	/* required element of type xsd:boolean */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 24; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREVerifyTimeStampResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREVerifyTimeStampResponse() : soap(NULL) { }
	virtual ~WS1__SOF_USCOREVerifyTimeStampResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREPubKeyEncrypt
#define SOAP_TYPE_WS1__SOF_USCOREPubKeyEncrypt (25)
/* WS1:SOF_PubKeyEncrypt */
class SOAP_CMAC WS1__SOF_USCOREPubKeyEncrypt
{
public:
	std::wstring *base64EncodeCert;	/* optional element of type xsd:string */
	std::wstring *inData;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 25; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREPubKeyEncrypt */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREPubKeyEncrypt() : base64EncodeCert(NULL), inData(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREPubKeyEncrypt() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREPubKeyEncryptResponse
#define SOAP_TYPE_WS1__SOF_USCOREPubKeyEncryptResponse (26)
/* WS1:SOF_PubKeyEncryptResponse */
class SOAP_CMAC WS1__SOF_USCOREPubKeyEncryptResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 26; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREPubKeyEncryptResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREPubKeyEncryptResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREPubKeyEncryptResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREVerifySignedFile
#define SOAP_TYPE_WS1__SOF_USCOREVerifySignedFile (27)
/* WS1:SOF_VerifySignedFile */
class SOAP_CMAC WS1__SOF_USCOREVerifySignedFile
{
public:
	std::wstring *base64EncodeCert;	/* optional element of type xsd:string */
	std::wstring *inFile;	/* optional element of type xsd:string */
	std::wstring *signValue;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 27; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREVerifySignedFile */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREVerifySignedFile() : base64EncodeCert(NULL), inFile(NULL), signValue(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREVerifySignedFile() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREVerifySignedFileResponse
#define SOAP_TYPE_WS1__SOF_USCOREVerifySignedFileResponse (28)
/* WS1:SOF_VerifySignedFileResponse */
class SOAP_CMAC WS1__SOF_USCOREVerifySignedFileResponse
{
public:
	bool return_;	/* RPC return element */	/* required element of type xsd:boolean */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 28; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREVerifySignedFileResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREVerifySignedFileResponse() : soap(NULL) { }
	virtual ~WS1__SOF_USCOREVerifySignedFileResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGetServerCertificate
#define SOAP_TYPE_WS1__SOF_USCOREGetServerCertificate (29)
/* WS1:SOF_GetServerCertificate */
class SOAP_CMAC WS1__SOF_USCOREGetServerCertificate
{
public:
	int certUsage;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 29; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGetServerCertificate */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGetServerCertificate() : soap(NULL) { }
	virtual ~WS1__SOF_USCOREGetServerCertificate() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGetServerCertificateResponse
#define SOAP_TYPE_WS1__SOF_USCOREGetServerCertificateResponse (30)
/* WS1:SOF_GetServerCertificateResponse */
class SOAP_CMAC WS1__SOF_USCOREGetServerCertificateResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 30; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGetServerCertificateResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGetServerCertificateResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREGetServerCertificateResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGetCertInfoByOid
#define SOAP_TYPE_WS1__SOF_USCOREGetCertInfoByOid (31)
/* WS1:SOF_GetCertInfoByOid */
class SOAP_CMAC WS1__SOF_USCOREGetCertInfoByOid
{
public:
	std::wstring *base64EncodeCert;	/* optional element of type xsd:string */
	std::wstring *oid;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 31; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGetCertInfoByOid */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGetCertInfoByOid() : base64EncodeCert(NULL), oid(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREGetCertInfoByOid() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGetCertInfoByOidResponse
#define SOAP_TYPE_WS1__SOF_USCOREGetCertInfoByOidResponse (32)
/* WS1:SOF_GetCertInfoByOidResponse */
class SOAP_CMAC WS1__SOF_USCOREGetCertInfoByOidResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 32; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGetCertInfoByOidResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGetCertInfoByOidResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREGetCertInfoByOidResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREDelCertTrustList
#define SOAP_TYPE_WS1__SOF_USCOREDelCertTrustList (33)
/* WS1:SOF_DelCertTrustList */
class SOAP_CMAC WS1__SOF_USCOREDelCertTrustList
{
public:
	std::wstring *fCtlAltname;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 33; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREDelCertTrustList */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREDelCertTrustList() : fCtlAltname(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREDelCertTrustList() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREDelCertTrustListResponse
#define SOAP_TYPE_WS1__SOF_USCOREDelCertTrustListResponse (34)
/* WS1:SOF_DelCertTrustListResponse */
class SOAP_CMAC WS1__SOF_USCOREDelCertTrustListResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 34; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREDelCertTrustListResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREDelCertTrustListResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREDelCertTrustListResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGetXMLSignatureInfo
#define SOAP_TYPE_WS1__SOF_USCOREGetXMLSignatureInfo (35)
/* WS1:SOF_GetXMLSignatureInfo */
class SOAP_CMAC WS1__SOF_USCOREGetXMLSignatureInfo
{
public:
	std::wstring *XMLSignedData;	/* optional element of type xsd:string */
	short type;	/* required element of type xsd:short */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 35; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGetXMLSignatureInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGetXMLSignatureInfo() : XMLSignedData(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREGetXMLSignatureInfo() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGetXMLSignatureInfoResponse
#define SOAP_TYPE_WS1__SOF_USCOREGetXMLSignatureInfoResponse (36)
/* WS1:SOF_GetXMLSignatureInfoResponse */
class SOAP_CMAC WS1__SOF_USCOREGetXMLSignatureInfoResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 36; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGetXMLSignatureInfoResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGetXMLSignatureInfoResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREGetXMLSignatureInfoResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREVerifySignedDataXML
#define SOAP_TYPE_WS1__SOF_USCOREVerifySignedDataXML (37)
/* WS1:SOF_VerifySignedDataXML */
class SOAP_CMAC WS1__SOF_USCOREVerifySignedDataXML
{
public:
	std::wstring *inData;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 37; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREVerifySignedDataXML */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREVerifySignedDataXML() : inData(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREVerifySignedDataXML() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREVerifySignedDataXMLResponse
#define SOAP_TYPE_WS1__SOF_USCOREVerifySignedDataXMLResponse (38)
/* WS1:SOF_VerifySignedDataXMLResponse */
class SOAP_CMAC WS1__SOF_USCOREVerifySignedDataXMLResponse
{
public:
	bool return_;	/* RPC return element */	/* required element of type xsd:boolean */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 38; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREVerifySignedDataXMLResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREVerifySignedDataXMLResponse() : soap(NULL) { }
	virtual ~WS1__SOF_USCOREVerifySignedDataXMLResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORESignData
#define SOAP_TYPE_WS1__SOF_USCORESignData (39)
/* WS1:SOF_SignData */
class SOAP_CMAC WS1__SOF_USCORESignData
{
public:
	std::wstring *inData;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 39; } /* = unique id SOAP_TYPE_WS1__SOF_USCORESignData */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORESignData() : inData(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCORESignData() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORESignDataResponse
#define SOAP_TYPE_WS1__SOF_USCORESignDataResponse (40)
/* WS1:SOF_SignDataResponse */
class SOAP_CMAC WS1__SOF_USCORESignDataResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 40; } /* = unique id SOAP_TYPE_WS1__SOF_USCORESignDataResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORESignDataResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCORESignDataResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORESignFile
#define SOAP_TYPE_WS1__SOF_USCORESignFile (41)
/* WS1:SOF_SignFile */
class SOAP_CMAC WS1__SOF_USCORESignFile
{
public:
	std::wstring *inFile;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 41; } /* = unique id SOAP_TYPE_WS1__SOF_USCORESignFile */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORESignFile() : inFile(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCORESignFile() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORESignFileResponse
#define SOAP_TYPE_WS1__SOF_USCORESignFileResponse (42)
/* WS1:SOF_SignFileResponse */
class SOAP_CMAC WS1__SOF_USCORESignFileResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 42; } /* = unique id SOAP_TYPE_WS1__SOF_USCORESignFileResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORESignFileResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCORESignFileResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGetInstance
#define SOAP_TYPE_WS1__SOF_USCOREGetInstance (43)
/* WS1:SOF_GetInstance */
class SOAP_CMAC WS1__SOF_USCOREGetInstance
{
public:
	std::wstring *appName;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 43; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGetInstance */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGetInstance() : appName(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREGetInstance() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGetInstanceResponse
#define SOAP_TYPE_WS1__SOF_USCOREGetInstanceResponse (44)
/* WS1:SOF_GetInstanceResponse */
class SOAP_CMAC WS1__SOF_USCOREGetInstanceResponse
{
public:
	class WS1__sofSecurityEngineDeal *return_;	/* RPC return element */	/* optional element of type WS1:sofSecurityEngineDeal */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 44; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGetInstanceResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGetInstanceResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREGetInstanceResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__sofSecurityEngineDeal
#define SOAP_TYPE_WS1__sofSecurityEngineDeal (45)
/* WS1:sofSecurityEngineDeal */
class SOAP_CMAC WS1__sofSecurityEngineDeal
{
public:
	std::wstring *alias;	/* optional element of type xsd:string */
	std::wstring *encryption;	/* optional element of type xsd:string */
	std::wstring *sessionID;	/* optional element of type xsd:string */
	std::wstring *signature;	/* optional element of type xsd:string */
	std::wstring *valcrl;	/* optional element of type xsd:string */
	std::wstring *valpath;	/* optional element of type xsd:string */
	std::wstring *valtime;	/* optional element of type xsd:string */
	std::wstring *webAppName;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 45; } /* = unique id SOAP_TYPE_WS1__sofSecurityEngineDeal */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__sofSecurityEngineDeal() : alias(NULL), encryption(NULL), sessionID(NULL), signature(NULL), valcrl(NULL), valpath(NULL), valtime(NULL), webAppName(NULL), soap(NULL) { }
	virtual ~WS1__sofSecurityEngineDeal() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREPriKeyDecrypt
#define SOAP_TYPE_WS1__SOF_USCOREPriKeyDecrypt (46)
/* WS1:SOF_PriKeyDecrypt */
class SOAP_CMAC WS1__SOF_USCOREPriKeyDecrypt
{
public:
	std::wstring *inData;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 46; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREPriKeyDecrypt */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREPriKeyDecrypt() : inData(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREPriKeyDecrypt() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREPriKeyDecryptResponse
#define SOAP_TYPE_WS1__SOF_USCOREPriKeyDecryptResponse (47)
/* WS1:SOF_PriKeyDecryptResponse */
class SOAP_CMAC WS1__SOF_USCOREPriKeyDecryptResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 47; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREPriKeyDecryptResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREPriKeyDecryptResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREPriKeyDecryptResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGenRandom
#define SOAP_TYPE_WS1__SOF_USCOREGenRandom (48)
/* WS1:SOF_GenRandom */
class SOAP_CMAC WS1__SOF_USCOREGenRandom
{
public:
	int len;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 48; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGenRandom */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGenRandom() : soap(NULL) { }
	virtual ~WS1__SOF_USCOREGenRandom() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGenRandomResponse
#define SOAP_TYPE_WS1__SOF_USCOREGenRandomResponse (49)
/* WS1:SOF_GenRandomResponse */
class SOAP_CMAC WS1__SOF_USCOREGenRandomResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 49; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGenRandomResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGenRandomResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREGenRandomResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORESetWebAppName
#define SOAP_TYPE_WS1__SOF_USCORESetWebAppName (50)
/* WS1:SOF_SetWebAppName */
class SOAP_CMAC WS1__SOF_USCORESetWebAppName
{
public:
	std::wstring *webAppName;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 50; } /* = unique id SOAP_TYPE_WS1__SOF_USCORESetWebAppName */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORESetWebAppName() : webAppName(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCORESetWebAppName() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORESetWebAppNameResponse
#define SOAP_TYPE_WS1__SOF_USCORESetWebAppNameResponse (51)
/* WS1:SOF_SetWebAppNameResponse */
class SOAP_CMAC WS1__SOF_USCORESetWebAppNameResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 51; } /* = unique id SOAP_TYPE_WS1__SOF_USCORESetWebAppNameResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORESetWebAppNameResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCORESetWebAppNameResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGetSignMethod
#define SOAP_TYPE_WS1__SOF_USCOREGetSignMethod (52)
/* WS1:SOF_GetSignMethod */
class SOAP_CMAC WS1__SOF_USCOREGetSignMethod
{
public:
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 52; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGetSignMethod */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGetSignMethod() : soap(NULL) { }
	virtual ~WS1__SOF_USCOREGetSignMethod() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGetSignMethodResponse
#define SOAP_TYPE_WS1__SOF_USCOREGetSignMethodResponse (53)
/* WS1:SOF_GetSignMethodResponse */
class SOAP_CMAC WS1__SOF_USCOREGetSignMethodResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 53; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGetSignMethodResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGetSignMethodResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREGetSignMethodResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORESetEncryptMethod
#define SOAP_TYPE_WS1__SOF_USCORESetEncryptMethod (54)
/* WS1:SOF_SetEncryptMethod */
class SOAP_CMAC WS1__SOF_USCORESetEncryptMethod
{
public:
	int encryptMethod;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 54; } /* = unique id SOAP_TYPE_WS1__SOF_USCORESetEncryptMethod */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORESetEncryptMethod() : soap(NULL) { }
	virtual ~WS1__SOF_USCORESetEncryptMethod() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORESetEncryptMethodResponse
#define SOAP_TYPE_WS1__SOF_USCORESetEncryptMethodResponse (55)
/* WS1:SOF_SetEncryptMethodResponse */
class SOAP_CMAC WS1__SOF_USCORESetEncryptMethodResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 55; } /* = unique id SOAP_TYPE_WS1__SOF_USCORESetEncryptMethodResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORESetEncryptMethodResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCORESetEncryptMethodResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORECreateTimeStampRequest
#define SOAP_TYPE_WS1__SOF_USCORECreateTimeStampRequest (56)
/* WS1:SOF_CreateTimeStampRequest */
class SOAP_CMAC WS1__SOF_USCORECreateTimeStampRequest
{
public:
	std::wstring *inData;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 56; } /* = unique id SOAP_TYPE_WS1__SOF_USCORECreateTimeStampRequest */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORECreateTimeStampRequest() : inData(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCORECreateTimeStampRequest() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORECreateTimeStampRequestResponse
#define SOAP_TYPE_WS1__SOF_USCORECreateTimeStampRequestResponse (57)
/* WS1:SOF_CreateTimeStampRequestResponse */
class SOAP_CMAC WS1__SOF_USCORECreateTimeStampRequestResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 57; } /* = unique id SOAP_TYPE_WS1__SOF_USCORECreateTimeStampRequestResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORECreateTimeStampRequestResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCORECreateTimeStampRequestResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGetEncryptMethod
#define SOAP_TYPE_WS1__SOF_USCOREGetEncryptMethod (58)
/* WS1:SOF_GetEncryptMethod */
class SOAP_CMAC WS1__SOF_USCOREGetEncryptMethod
{
public:
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 58; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGetEncryptMethod */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGetEncryptMethod() : soap(NULL) { }
	virtual ~WS1__SOF_USCOREGetEncryptMethod() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGetEncryptMethodResponse
#define SOAP_TYPE_WS1__SOF_USCOREGetEncryptMethodResponse (59)
/* WS1:SOF_GetEncryptMethodResponse */
class SOAP_CMAC WS1__SOF_USCOREGetEncryptMethodResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 59; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGetEncryptMethodResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGetEncryptMethodResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREGetEncryptMethodResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORECreateTimeStampResponse
#define SOAP_TYPE_WS1__SOF_USCORECreateTimeStampResponse (60)
/* WS1:SOF_CreateTimeStampResponse */
class SOAP_CMAC WS1__SOF_USCORECreateTimeStampResponse
{
public:
	std::wstring *inData;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 60; } /* = unique id SOAP_TYPE_WS1__SOF_USCORECreateTimeStampResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORECreateTimeStampResponse() : inData(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCORECreateTimeStampResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORECreateTimeStampResponseResponse
#define SOAP_TYPE_WS1__SOF_USCORECreateTimeStampResponseResponse (61)
/* WS1:SOF_CreateTimeStampResponseResponse */
class SOAP_CMAC WS1__SOF_USCORECreateTimeStampResponseResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 61; } /* = unique id SOAP_TYPE_WS1__SOF_USCORECreateTimeStampResponseResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORECreateTimeStampResponseResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCORECreateTimeStampResponseResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREValidateCert
#define SOAP_TYPE_WS1__SOF_USCOREValidateCert (62)
/* WS1:SOF_ValidateCert */
class SOAP_CMAC WS1__SOF_USCOREValidateCert
{
public:
	std::wstring *base64EncodeCert;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 62; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREValidateCert */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREValidateCert() : base64EncodeCert(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREValidateCert() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREValidateCertResponse
#define SOAP_TYPE_WS1__SOF_USCOREValidateCertResponse (63)
/* WS1:SOF_ValidateCertResponse */
class SOAP_CMAC WS1__SOF_USCOREValidateCertResponse
{
public:
	int return_;	/* RPC return element */	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 63; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREValidateCertResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREValidateCertResponse() : soap(NULL) { }
	virtual ~WS1__SOF_USCOREValidateCertResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__DeleteFile
#define SOAP_TYPE_WS1__DeleteFile (64)
/* WS1:DeleteFile */
class SOAP_CMAC WS1__DeleteFile
{
public:
	std::wstring *fileName;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 64; } /* = unique id SOAP_TYPE_WS1__DeleteFile */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__DeleteFile() : fileName(NULL), soap(NULL) { }
	virtual ~WS1__DeleteFile() { }
};
#endif

#ifndef SOAP_TYPE_WS1__DeleteFileResponse
#define SOAP_TYPE_WS1__DeleteFileResponse (65)
/* WS1:DeleteFileResponse */
class SOAP_CMAC WS1__DeleteFileResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 65; } /* = unique id SOAP_TYPE_WS1__DeleteFileResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__DeleteFileResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__DeleteFileResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__GetFile
#define SOAP_TYPE_WS1__GetFile (66)
/* WS1:GetFile */
class SOAP_CMAC WS1__GetFile
{
public:
	std::wstring *requestFileName;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 66; } /* = unique id SOAP_TYPE_WS1__GetFile */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__GetFile() : requestFileName(NULL), soap(NULL) { }
	virtual ~WS1__GetFile() { }
};
#endif

#ifndef SOAP_TYPE_WS1__GetFileResponse
#define SOAP_TYPE_WS1__GetFileResponse (67)
/* WS1:GetFileResponse */
class SOAP_CMAC WS1__GetFileResponse
{
public:
	xsd__base64Binary *return_;	/* RPC return element */	/* optional element of type xsd:base64Binary */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 67; } /* = unique id SOAP_TYPE_WS1__GetFileResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__GetFileResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__GetFileResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREDecryptFile
#define SOAP_TYPE_WS1__SOF_USCOREDecryptFile (68)
/* WS1:SOF_DecryptFile */
class SOAP_CMAC WS1__SOF_USCOREDecryptFile
{
public:
	std::wstring *key;	/* optional element of type xsd:string */
	std::wstring *inFile;	/* optional element of type xsd:string */
	std::wstring *outFile;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 68; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREDecryptFile */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREDecryptFile() : key(NULL), inFile(NULL), outFile(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREDecryptFile() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREDecryptFileResponse
#define SOAP_TYPE_WS1__SOF_USCOREDecryptFileResponse (69)
/* WS1:SOF_DecryptFileResponse */
class SOAP_CMAC WS1__SOF_USCOREDecryptFileResponse
{
public:
	bool return_;	/* RPC return element */	/* required element of type xsd:boolean */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 69; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREDecryptFileResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREDecryptFileResponse() : soap(NULL) { }
	virtual ~WS1__SOF_USCOREDecryptFileResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORESetSignMethod
#define SOAP_TYPE_WS1__SOF_USCORESetSignMethod (70)
/* WS1:SOF_SetSignMethod */
class SOAP_CMAC WS1__SOF_USCORESetSignMethod
{
public:
	int signMethod;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 70; } /* = unique id SOAP_TYPE_WS1__SOF_USCORESetSignMethod */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORESetSignMethod() : soap(NULL) { }
	virtual ~WS1__SOF_USCORESetSignMethod() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORESetSignMethodResponse
#define SOAP_TYPE_WS1__SOF_USCORESetSignMethodResponse (71)
/* WS1:SOF_SetSignMethodResponse */
class SOAP_CMAC WS1__SOF_USCORESetSignMethodResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 71; } /* = unique id SOAP_TYPE_WS1__SOF_USCORESetSignMethodResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORESetSignMethodResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCORESetSignMethodResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGetTimeStampInfo
#define SOAP_TYPE_WS1__SOF_USCOREGetTimeStampInfo (72)
/* WS1:SOF_GetTimeStampInfo */
class SOAP_CMAC WS1__SOF_USCOREGetTimeStampInfo
{
public:
	std::wstring *tsResponseData;	/* optional element of type xsd:string */
	int type;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 72; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGetTimeStampInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGetTimeStampInfo() : tsResponseData(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREGetTimeStampInfo() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGetTimeStampInfoResponse
#define SOAP_TYPE_WS1__SOF_USCOREGetTimeStampInfoResponse (73)
/* WS1:SOF_GetTimeStampInfoResponse */
class SOAP_CMAC WS1__SOF_USCOREGetTimeStampInfoResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 73; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGetTimeStampInfoResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGetTimeStampInfoResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREGetTimeStampInfoResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORESignDataByP7
#define SOAP_TYPE_WS1__SOF_USCORESignDataByP7 (74)
/* WS1:SOF_SignDataByP7 */
class SOAP_CMAC WS1__SOF_USCORESignDataByP7
{
public:
	std::wstring *inData;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 74; } /* = unique id SOAP_TYPE_WS1__SOF_USCORESignDataByP7 */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORESignDataByP7() : inData(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCORESignDataByP7() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORESignDataByP7Response
#define SOAP_TYPE_WS1__SOF_USCORESignDataByP7Response (75)
/* WS1:SOF_SignDataByP7Response */
class SOAP_CMAC WS1__SOF_USCORESignDataByP7Response
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 75; } /* = unique id SOAP_TYPE_WS1__SOF_USCORESignDataByP7Response */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORESignDataByP7Response() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCORESignDataByP7Response() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREEncryptFile
#define SOAP_TYPE_WS1__SOF_USCOREEncryptFile (76)
/* WS1:SOF_EncryptFile */
class SOAP_CMAC WS1__SOF_USCOREEncryptFile
{
public:
	std::wstring *key;	/* optional element of type xsd:string */
	std::wstring *inFile;	/* optional element of type xsd:string */
	std::wstring *outFile;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 76; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREEncryptFile */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREEncryptFile() : key(NULL), inFile(NULL), outFile(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREEncryptFile() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREEncryptFileResponse
#define SOAP_TYPE_WS1__SOF_USCOREEncryptFileResponse (77)
/* WS1:SOF_EncryptFileResponse */
class SOAP_CMAC WS1__SOF_USCOREEncryptFileResponse
{
public:
	bool return_;	/* RPC return element */	/* required element of type xsd:boolean */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 77; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREEncryptFileResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREEncryptFileResponse() : soap(NULL) { }
	virtual ~WS1__SOF_USCOREEncryptFileResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORESignDataXML
#define SOAP_TYPE_WS1__SOF_USCORESignDataXML (78)
/* WS1:SOF_SignDataXML */
class SOAP_CMAC WS1__SOF_USCORESignDataXML
{
public:
	std::wstring *inData;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 78; } /* = unique id SOAP_TYPE_WS1__SOF_USCORESignDataXML */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORESignDataXML() : inData(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCORESignDataXML() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCORESignDataXMLResponse
#define SOAP_TYPE_WS1__SOF_USCORESignDataXMLResponse (79)
/* WS1:SOF_SignDataXMLResponse */
class SOAP_CMAC WS1__SOF_USCORESignDataXMLResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 79; } /* = unique id SOAP_TYPE_WS1__SOF_USCORESignDataXMLResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCORESignDataXMLResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCORESignDataXMLResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREDecryptData
#define SOAP_TYPE_WS1__SOF_USCOREDecryptData (80)
/* WS1:SOF_DecryptData */
class SOAP_CMAC WS1__SOF_USCOREDecryptData
{
public:
	std::wstring *key;	/* optional element of type xsd:string */
	std::wstring *inData;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 80; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREDecryptData */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREDecryptData() : key(NULL), inData(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREDecryptData() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREDecryptDataResponse
#define SOAP_TYPE_WS1__SOF_USCOREDecryptDataResponse (81)
/* WS1:SOF_DecryptDataResponse */
class SOAP_CMAC WS1__SOF_USCOREDecryptDataResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 81; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREDecryptDataResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREDecryptDataResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREDecryptDataResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREQueryCertTrustListAltNames
#define SOAP_TYPE_WS1__SOF_USCOREQueryCertTrustListAltNames (82)
/* WS1:SOF_QueryCertTrustListAltNames */
class SOAP_CMAC WS1__SOF_USCOREQueryCertTrustListAltNames
{
public:
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 82; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREQueryCertTrustListAltNames */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREQueryCertTrustListAltNames() : soap(NULL) { }
	virtual ~WS1__SOF_USCOREQueryCertTrustListAltNames() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREQueryCertTrustListAltNamesResponse
#define SOAP_TYPE_WS1__SOF_USCOREQueryCertTrustListAltNamesResponse (83)
/* WS1:SOF_QueryCertTrustListAltNamesResponse */
class SOAP_CMAC WS1__SOF_USCOREQueryCertTrustListAltNamesResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 83; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREQueryCertTrustListAltNamesResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREQueryCertTrustListAltNamesResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREQueryCertTrustListAltNamesResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGetCertInfo
#define SOAP_TYPE_WS1__SOF_USCOREGetCertInfo (84)
/* WS1:SOF_GetCertInfo */
class SOAP_CMAC WS1__SOF_USCOREGetCertInfo
{
public:
	std::wstring *base64EncodeCert;	/* optional element of type xsd:string */
	int type;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 84; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGetCertInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGetCertInfo() : base64EncodeCert(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREGetCertInfo() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREGetCertInfoResponse
#define SOAP_TYPE_WS1__SOF_USCOREGetCertInfoResponse (85)
/* WS1:SOF_GetCertInfoResponse */
class SOAP_CMAC WS1__SOF_USCOREGetCertInfoResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 85; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREGetCertInfoResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREGetCertInfoResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREGetCertInfoResponse() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREEncryptData
#define SOAP_TYPE_WS1__SOF_USCOREEncryptData (86)
/* WS1:SOF_EncryptData */
class SOAP_CMAC WS1__SOF_USCOREEncryptData
{
public:
	std::wstring *key;	/* optional element of type xsd:string */
	std::wstring *inData;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 86; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREEncryptData */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREEncryptData() : key(NULL), inData(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREEncryptData() { }
};
#endif

#ifndef SOAP_TYPE_WS1__SOF_USCOREEncryptDataResponse
#define SOAP_TYPE_WS1__SOF_USCOREEncryptDataResponse (87)
/* WS1:SOF_EncryptDataResponse */
class SOAP_CMAC WS1__SOF_USCOREEncryptDataResponse
{
public:
	std::wstring *return_;	/* RPC return element */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 87; } /* = unique id SOAP_TYPE_WS1__SOF_USCOREEncryptDataResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         WS1__SOF_USCOREEncryptDataResponse() : return_(NULL), soap(NULL) { }
	virtual ~WS1__SOF_USCOREEncryptDataResponse() { }
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREVerifySignedData
#define SOAP_TYPE___WS1__SOF_USCOREVerifySignedData (97)
/* Operation wrapper: */
struct __WS1__SOF_USCOREVerifySignedData
{
public:
	WS1__SOF_USCOREVerifySignedData *WS1__SOF_USCOREVerifySignedData_;	/* optional element of type WS1:SOF_VerifySignedData */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREQueryCertTrustList
#define SOAP_TYPE___WS1__SOF_USCOREQueryCertTrustList (101)
/* Operation wrapper: */
struct __WS1__SOF_USCOREQueryCertTrustList
{
public:
	WS1__SOF_USCOREQueryCertTrustList *WS1__SOF_USCOREQueryCertTrustList_;	/* optional element of type WS1:SOF_QueryCertTrustList */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREGetP7SignDataInfo
#define SOAP_TYPE___WS1__SOF_USCOREGetP7SignDataInfo (105)
/* Operation wrapper: */
struct __WS1__SOF_USCOREGetP7SignDataInfo
{
public:
	WS1__SOF_USCOREGetP7SignDataInfo *WS1__SOF_USCOREGetP7SignDataInfo_;	/* optional element of type WS1:SOF_GetP7SignDataInfo */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCORESetCertTrustList
#define SOAP_TYPE___WS1__SOF_USCORESetCertTrustList (109)
/* Operation wrapper: */
struct __WS1__SOF_USCORESetCertTrustList
{
public:
	WS1__SOF_USCORESetCertTrustList *WS1__SOF_USCORESetCertTrustList_;	/* optional element of type WS1:SOF_SetCertTrustList */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREVerifySignedDataByP7
#define SOAP_TYPE___WS1__SOF_USCOREVerifySignedDataByP7 (113)
/* Operation wrapper: */
struct __WS1__SOF_USCOREVerifySignedDataByP7
{
public:
	WS1__SOF_USCOREVerifySignedDataByP7 *WS1__SOF_USCOREVerifySignedDataByP7_;	/* optional element of type WS1:SOF_VerifySignedDataByP7 */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREPubKeyEncrypt
#define SOAP_TYPE___WS1__SOF_USCOREPubKeyEncrypt (117)
/* Operation wrapper: */
struct __WS1__SOF_USCOREPubKeyEncrypt
{
public:
	WS1__SOF_USCOREPubKeyEncrypt *WS1__SOF_USCOREPubKeyEncrypt_;	/* optional element of type WS1:SOF_PubKeyEncrypt */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREVerifyTimeStamp
#define SOAP_TYPE___WS1__SOF_USCOREVerifyTimeStamp (121)
/* Operation wrapper: */
struct __WS1__SOF_USCOREVerifyTimeStamp
{
public:
	WS1__SOF_USCOREVerifyTimeStamp *WS1__SOF_USCOREVerifyTimeStamp_;	/* optional element of type WS1:SOF_VerifyTimeStamp */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREVerifySignedFile
#define SOAP_TYPE___WS1__SOF_USCOREVerifySignedFile (125)
/* Operation wrapper: */
struct __WS1__SOF_USCOREVerifySignedFile
{
public:
	WS1__SOF_USCOREVerifySignedFile *WS1__SOF_USCOREVerifySignedFile_;	/* optional element of type WS1:SOF_VerifySignedFile */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREGetCertInfoByOid
#define SOAP_TYPE___WS1__SOF_USCOREGetCertInfoByOid (129)
/* Operation wrapper: */
struct __WS1__SOF_USCOREGetCertInfoByOid
{
public:
	WS1__SOF_USCOREGetCertInfoByOid *WS1__SOF_USCOREGetCertInfoByOid_;	/* optional element of type WS1:SOF_GetCertInfoByOid */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREGetServerCertificate
#define SOAP_TYPE___WS1__SOF_USCOREGetServerCertificate (133)
/* Operation wrapper: */
struct __WS1__SOF_USCOREGetServerCertificate
{
public:
	WS1__SOF_USCOREGetServerCertificate *WS1__SOF_USCOREGetServerCertificate_;	/* optional element of type WS1:SOF_GetServerCertificate */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREDelCertTrustList
#define SOAP_TYPE___WS1__SOF_USCOREDelCertTrustList (137)
/* Operation wrapper: */
struct __WS1__SOF_USCOREDelCertTrustList
{
public:
	WS1__SOF_USCOREDelCertTrustList *WS1__SOF_USCOREDelCertTrustList_;	/* optional element of type WS1:SOF_DelCertTrustList */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREGetXMLSignatureInfo
#define SOAP_TYPE___WS1__SOF_USCOREGetXMLSignatureInfo (141)
/* Operation wrapper: */
struct __WS1__SOF_USCOREGetXMLSignatureInfo
{
public:
	WS1__SOF_USCOREGetXMLSignatureInfo *WS1__SOF_USCOREGetXMLSignatureInfo_;	/* optional element of type WS1:SOF_GetXMLSignatureInfo */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCORESignData
#define SOAP_TYPE___WS1__SOF_USCORESignData (145)
/* Operation wrapper: */
struct __WS1__SOF_USCORESignData
{
public:
	WS1__SOF_USCORESignData *WS1__SOF_USCORESignData_;	/* optional element of type WS1:SOF_SignData */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREVerifySignedDataXML
#define SOAP_TYPE___WS1__SOF_USCOREVerifySignedDataXML (149)
/* Operation wrapper: */
struct __WS1__SOF_USCOREVerifySignedDataXML
{
public:
	WS1__SOF_USCOREVerifySignedDataXML *WS1__SOF_USCOREVerifySignedDataXML_;	/* optional element of type WS1:SOF_VerifySignedDataXML */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCORESignFile
#define SOAP_TYPE___WS1__SOF_USCORESignFile (153)
/* Operation wrapper: */
struct __WS1__SOF_USCORESignFile
{
public:
	WS1__SOF_USCORESignFile *WS1__SOF_USCORESignFile_;	/* optional element of type WS1:SOF_SignFile */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREGetInstance
#define SOAP_TYPE___WS1__SOF_USCOREGetInstance (157)
/* Operation wrapper: */
struct __WS1__SOF_USCOREGetInstance
{
public:
	WS1__SOF_USCOREGetInstance *WS1__SOF_USCOREGetInstance_;	/* optional element of type WS1:SOF_GetInstance */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREPriKeyDecrypt
#define SOAP_TYPE___WS1__SOF_USCOREPriKeyDecrypt (161)
/* Operation wrapper: */
struct __WS1__SOF_USCOREPriKeyDecrypt
{
public:
	WS1__SOF_USCOREPriKeyDecrypt *WS1__SOF_USCOREPriKeyDecrypt_;	/* optional element of type WS1:SOF_PriKeyDecrypt */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREGenRandom
#define SOAP_TYPE___WS1__SOF_USCOREGenRandom (165)
/* Operation wrapper: */
struct __WS1__SOF_USCOREGenRandom
{
public:
	WS1__SOF_USCOREGenRandom *WS1__SOF_USCOREGenRandom_;	/* optional element of type WS1:SOF_GenRandom */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREGetSignMethod
#define SOAP_TYPE___WS1__SOF_USCOREGetSignMethod (169)
/* Operation wrapper: */
struct __WS1__SOF_USCOREGetSignMethod
{
public:
	WS1__SOF_USCOREGetSignMethod *WS1__SOF_USCOREGetSignMethod_;	/* optional element of type WS1:SOF_GetSignMethod */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCORESetWebAppName
#define SOAP_TYPE___WS1__SOF_USCORESetWebAppName (173)
/* Operation wrapper: */
struct __WS1__SOF_USCORESetWebAppName
{
public:
	WS1__SOF_USCORESetWebAppName *WS1__SOF_USCORESetWebAppName_;	/* optional element of type WS1:SOF_SetWebAppName */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCORESetEncryptMethod
#define SOAP_TYPE___WS1__SOF_USCORESetEncryptMethod (177)
/* Operation wrapper: */
struct __WS1__SOF_USCORESetEncryptMethod
{
public:
	WS1__SOF_USCORESetEncryptMethod *WS1__SOF_USCORESetEncryptMethod_;	/* optional element of type WS1:SOF_SetEncryptMethod */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCORECreateTimeStampRequest
#define SOAP_TYPE___WS1__SOF_USCORECreateTimeStampRequest (181)
/* Operation wrapper: */
struct __WS1__SOF_USCORECreateTimeStampRequest
{
public:
	WS1__SOF_USCORECreateTimeStampRequest *WS1__SOF_USCORECreateTimeStampRequest_;	/* optional element of type WS1:SOF_CreateTimeStampRequest */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREGetEncryptMethod
#define SOAP_TYPE___WS1__SOF_USCOREGetEncryptMethod (185)
/* Operation wrapper: */
struct __WS1__SOF_USCOREGetEncryptMethod
{
public:
	WS1__SOF_USCOREGetEncryptMethod *WS1__SOF_USCOREGetEncryptMethod_;	/* optional element of type WS1:SOF_GetEncryptMethod */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCORECreateTimeStampResponse
#define SOAP_TYPE___WS1__SOF_USCORECreateTimeStampResponse (189)
/* Operation wrapper: */
struct __WS1__SOF_USCORECreateTimeStampResponse
{
public:
	WS1__SOF_USCORECreateTimeStampResponse *WS1__SOF_USCORECreateTimeStampResponse_;	/* optional element of type WS1:SOF_CreateTimeStampResponse */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREValidateCert
#define SOAP_TYPE___WS1__SOF_USCOREValidateCert (193)
/* Operation wrapper: */
struct __WS1__SOF_USCOREValidateCert
{
public:
	WS1__SOF_USCOREValidateCert *WS1__SOF_USCOREValidateCert_;	/* optional element of type WS1:SOF_ValidateCert */
};
#endif

#ifndef SOAP_TYPE___WS1__DeleteFile
#define SOAP_TYPE___WS1__DeleteFile (197)
/* Operation wrapper: */
struct __WS1__DeleteFile
{
public:
	WS1__DeleteFile *WS1__DeleteFile_;	/* optional element of type WS1:DeleteFile */
};
#endif

#ifndef SOAP_TYPE___WS1__GetFile
#define SOAP_TYPE___WS1__GetFile (201)
/* Operation wrapper: */
struct __WS1__GetFile
{
public:
	WS1__GetFile *WS1__GetFile_;	/* optional element of type WS1:GetFile */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREDecryptFile
#define SOAP_TYPE___WS1__SOF_USCOREDecryptFile (205)
/* Operation wrapper: */
struct __WS1__SOF_USCOREDecryptFile
{
public:
	WS1__SOF_USCOREDecryptFile *WS1__SOF_USCOREDecryptFile_;	/* optional element of type WS1:SOF_DecryptFile */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCORESetSignMethod
#define SOAP_TYPE___WS1__SOF_USCORESetSignMethod (209)
/* Operation wrapper: */
struct __WS1__SOF_USCORESetSignMethod
{
public:
	WS1__SOF_USCORESetSignMethod *WS1__SOF_USCORESetSignMethod_;	/* optional element of type WS1:SOF_SetSignMethod */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREGetTimeStampInfo
#define SOAP_TYPE___WS1__SOF_USCOREGetTimeStampInfo (213)
/* Operation wrapper: */
struct __WS1__SOF_USCOREGetTimeStampInfo
{
public:
	WS1__SOF_USCOREGetTimeStampInfo *WS1__SOF_USCOREGetTimeStampInfo_;	/* optional element of type WS1:SOF_GetTimeStampInfo */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREEncryptFile
#define SOAP_TYPE___WS1__SOF_USCOREEncryptFile (217)
/* Operation wrapper: */
struct __WS1__SOF_USCOREEncryptFile
{
public:
	WS1__SOF_USCOREEncryptFile *WS1__SOF_USCOREEncryptFile_;	/* optional element of type WS1:SOF_EncryptFile */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCORESignDataByP7
#define SOAP_TYPE___WS1__SOF_USCORESignDataByP7 (221)
/* Operation wrapper: */
struct __WS1__SOF_USCORESignDataByP7
{
public:
	WS1__SOF_USCORESignDataByP7 *WS1__SOF_USCORESignDataByP7_;	/* optional element of type WS1:SOF_SignDataByP7 */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREDecryptData
#define SOAP_TYPE___WS1__SOF_USCOREDecryptData (225)
/* Operation wrapper: */
struct __WS1__SOF_USCOREDecryptData
{
public:
	WS1__SOF_USCOREDecryptData *WS1__SOF_USCOREDecryptData_;	/* optional element of type WS1:SOF_DecryptData */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCORESignDataXML
#define SOAP_TYPE___WS1__SOF_USCORESignDataXML (229)
/* Operation wrapper: */
struct __WS1__SOF_USCORESignDataXML
{
public:
	WS1__SOF_USCORESignDataXML *WS1__SOF_USCORESignDataXML_;	/* optional element of type WS1:SOF_SignDataXML */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREGetCertInfo
#define SOAP_TYPE___WS1__SOF_USCOREGetCertInfo (233)
/* Operation wrapper: */
struct __WS1__SOF_USCOREGetCertInfo
{
public:
	WS1__SOF_USCOREGetCertInfo *WS1__SOF_USCOREGetCertInfo_;	/* optional element of type WS1:SOF_GetCertInfo */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREQueryCertTrustListAltNames
#define SOAP_TYPE___WS1__SOF_USCOREQueryCertTrustListAltNames (237)
/* Operation wrapper: */
struct __WS1__SOF_USCOREQueryCertTrustListAltNames
{
public:
	WS1__SOF_USCOREQueryCertTrustListAltNames *WS1__SOF_USCOREQueryCertTrustListAltNames_;	/* optional element of type WS1:SOF_QueryCertTrustListAltNames */
};
#endif

#ifndef SOAP_TYPE___WS1__SOF_USCOREEncryptData
#define SOAP_TYPE___WS1__SOF_USCOREEncryptData (241)
/* Operation wrapper: */
struct __WS1__SOF_USCOREEncryptData
{
public:
	WS1__SOF_USCOREEncryptData *WS1__SOF_USCOREEncryptData_;	/* optional element of type WS1:SOF_EncryptData */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (244)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	void *dummy;	/* transient */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (245)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (247)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (248)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (249)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (4)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif


/******************************************************************************\
 *                                                                            *
 * Typedef Synonyms                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREVerifySignedData(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREVerifySignedData *WS1__SOF_USCOREVerifySignedData_, WS1__SOF_USCOREVerifySignedDataResponse *WS1__SOF_USCOREVerifySignedDataResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREQueryCertTrustList(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREQueryCertTrustList *WS1__SOF_USCOREQueryCertTrustList_, WS1__SOF_USCOREQueryCertTrustListResponse *WS1__SOF_USCOREQueryCertTrustListResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREGetP7SignDataInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREGetP7SignDataInfo *WS1__SOF_USCOREGetP7SignDataInfo_, WS1__SOF_USCOREGetP7SignDataInfoResponse *WS1__SOF_USCOREGetP7SignDataInfoResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCORESetCertTrustList(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCORESetCertTrustList *WS1__SOF_USCORESetCertTrustList_, WS1__SOF_USCORESetCertTrustListResponse *WS1__SOF_USCORESetCertTrustListResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREVerifySignedDataByP7(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREVerifySignedDataByP7 *WS1__SOF_USCOREVerifySignedDataByP7_, WS1__SOF_USCOREVerifySignedDataByP7Response *WS1__SOF_USCOREVerifySignedDataByP7Response_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREPubKeyEncrypt(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREPubKeyEncrypt *WS1__SOF_USCOREPubKeyEncrypt_, WS1__SOF_USCOREPubKeyEncryptResponse *WS1__SOF_USCOREPubKeyEncryptResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREVerifyTimeStamp(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREVerifyTimeStamp *WS1__SOF_USCOREVerifyTimeStamp_, WS1__SOF_USCOREVerifyTimeStampResponse *WS1__SOF_USCOREVerifyTimeStampResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREVerifySignedFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREVerifySignedFile *WS1__SOF_USCOREVerifySignedFile_, WS1__SOF_USCOREVerifySignedFileResponse *WS1__SOF_USCOREVerifySignedFileResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREGetCertInfoByOid(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREGetCertInfoByOid *WS1__SOF_USCOREGetCertInfoByOid_, WS1__SOF_USCOREGetCertInfoByOidResponse *WS1__SOF_USCOREGetCertInfoByOidResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREGetServerCertificate(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREGetServerCertificate *WS1__SOF_USCOREGetServerCertificate_, WS1__SOF_USCOREGetServerCertificateResponse *WS1__SOF_USCOREGetServerCertificateResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREDelCertTrustList(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREDelCertTrustList *WS1__SOF_USCOREDelCertTrustList_, WS1__SOF_USCOREDelCertTrustListResponse *WS1__SOF_USCOREDelCertTrustListResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREGetXMLSignatureInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREGetXMLSignatureInfo *WS1__SOF_USCOREGetXMLSignatureInfo_, WS1__SOF_USCOREGetXMLSignatureInfoResponse *WS1__SOF_USCOREGetXMLSignatureInfoResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCORESignData(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCORESignData *WS1__SOF_USCORESignData_, WS1__SOF_USCORESignDataResponse *WS1__SOF_USCORESignDataResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREVerifySignedDataXML(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREVerifySignedDataXML *WS1__SOF_USCOREVerifySignedDataXML_, WS1__SOF_USCOREVerifySignedDataXMLResponse *WS1__SOF_USCOREVerifySignedDataXMLResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCORESignFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCORESignFile *WS1__SOF_USCORESignFile_, WS1__SOF_USCORESignFileResponse *WS1__SOF_USCORESignFileResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREGetInstance(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREGetInstance *WS1__SOF_USCOREGetInstance_, WS1__SOF_USCOREGetInstanceResponse *WS1__SOF_USCOREGetInstanceResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREPriKeyDecrypt(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREPriKeyDecrypt *WS1__SOF_USCOREPriKeyDecrypt_, WS1__SOF_USCOREPriKeyDecryptResponse *WS1__SOF_USCOREPriKeyDecryptResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREGenRandom(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREGenRandom *WS1__SOF_USCOREGenRandom_, WS1__SOF_USCOREGenRandomResponse *WS1__SOF_USCOREGenRandomResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREGetSignMethod(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREGetSignMethod *WS1__SOF_USCOREGetSignMethod_, WS1__SOF_USCOREGetSignMethodResponse *WS1__SOF_USCOREGetSignMethodResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCORESetWebAppName(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCORESetWebAppName *WS1__SOF_USCORESetWebAppName_, WS1__SOF_USCORESetWebAppNameResponse *WS1__SOF_USCORESetWebAppNameResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCORESetEncryptMethod(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCORESetEncryptMethod *WS1__SOF_USCORESetEncryptMethod_, WS1__SOF_USCORESetEncryptMethodResponse *WS1__SOF_USCORESetEncryptMethodResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCORECreateTimeStampRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCORECreateTimeStampRequest *WS1__SOF_USCORECreateTimeStampRequest_, WS1__SOF_USCORECreateTimeStampRequestResponse *WS1__SOF_USCORECreateTimeStampRequestResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREGetEncryptMethod(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREGetEncryptMethod *WS1__SOF_USCOREGetEncryptMethod_, WS1__SOF_USCOREGetEncryptMethodResponse *WS1__SOF_USCOREGetEncryptMethodResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCORECreateTimeStampResponse(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCORECreateTimeStampResponse *WS1__SOF_USCORECreateTimeStampResponse_, WS1__SOF_USCORECreateTimeStampResponseResponse *WS1__SOF_USCORECreateTimeStampResponseResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREValidateCert(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREValidateCert *WS1__SOF_USCOREValidateCert_, WS1__SOF_USCOREValidateCertResponse *WS1__SOF_USCOREValidateCertResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__DeleteFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__DeleteFile *WS1__DeleteFile_, WS1__DeleteFileResponse *WS1__DeleteFileResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__GetFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__GetFile *WS1__GetFile_, WS1__GetFileResponse *WS1__GetFileResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREDecryptFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREDecryptFile *WS1__SOF_USCOREDecryptFile_, WS1__SOF_USCOREDecryptFileResponse *WS1__SOF_USCOREDecryptFileResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCORESetSignMethod(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCORESetSignMethod *WS1__SOF_USCORESetSignMethod_, WS1__SOF_USCORESetSignMethodResponse *WS1__SOF_USCORESetSignMethodResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREGetTimeStampInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREGetTimeStampInfo *WS1__SOF_USCOREGetTimeStampInfo_, WS1__SOF_USCOREGetTimeStampInfoResponse *WS1__SOF_USCOREGetTimeStampInfoResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREEncryptFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREEncryptFile *WS1__SOF_USCOREEncryptFile_, WS1__SOF_USCOREEncryptFileResponse *WS1__SOF_USCOREEncryptFileResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCORESignDataByP7(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCORESignDataByP7 *WS1__SOF_USCORESignDataByP7_, WS1__SOF_USCORESignDataByP7Response *WS1__SOF_USCORESignDataByP7Response_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREDecryptData(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREDecryptData *WS1__SOF_USCOREDecryptData_, WS1__SOF_USCOREDecryptDataResponse *WS1__SOF_USCOREDecryptDataResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCORESignDataXML(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCORESignDataXML *WS1__SOF_USCORESignDataXML_, WS1__SOF_USCORESignDataXMLResponse *WS1__SOF_USCORESignDataXMLResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREGetCertInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREGetCertInfo *WS1__SOF_USCOREGetCertInfo_, WS1__SOF_USCOREGetCertInfoResponse *WS1__SOF_USCOREGetCertInfoResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREQueryCertTrustListAltNames(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREQueryCertTrustListAltNames *WS1__SOF_USCOREQueryCertTrustListAltNames_, WS1__SOF_USCOREQueryCertTrustListAltNamesResponse *WS1__SOF_USCOREQueryCertTrustListAltNamesResponse_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__SOF_USCOREEncryptData(struct soap *soap, const char *soap_endpoint, const char *soap_action, WS1__SOF_USCOREEncryptData *WS1__SOF_USCOREEncryptData_, WS1__SOF_USCOREEncryptDataResponse *WS1__SOF_USCOREEncryptDataResponse_);

#endif

/* End of soapStub.h */
